#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

/*
   R G B
*/


static int getSteps(char a, char b)
{
  if (a==b)
    return 0;

  if (a=='R')
  {
    if (b=='G') return 1;
    if (b=='B') return 2;
  }
  if(a=='G')
  {
    if (b=='R') return 2;
    if (b=='B') return 1;
  }
  if (a=='B')
  {
    if (b=='G') return 2;
    if (b=='R') return 1;
  }
}

/*
   R G B
*/

static char getNext(char c, int steps)
{
  if (steps<0)
    steps += 3;
  if (steps==0)
  {
    return c;
  }
  if(steps==1)
  {
    if (c=='G') return 'B';
    if (c=='R') return 'G';
    if (c=='B') return 'R';
  }
  if (steps==2)
  {
    if (c=='G') return 'R';
    if (c=='R') return 'B';
    if (c=='B') return 'G';
  }

  return 0;
}

static int mix(char a, char b)
{
  if (a==b)
    return a;

  if (a=='R')
  {
    if (b=='G') return 'B';
    if (b=='B') return 'G';
  }
  if(a=='G')
  {
    if (b=='R') return 'B';
    if (b=='B') return 'R';
  }
  if (a=='B')
  {
    if (b=='G') return 'R';
    if (b=='R') return 'G';
  }
  printf("unhandled characters %c and %c\n",a,b);
  return 0;
}

char defaultMix( char *ptr, int length)
{
  int i,j,n;
  char *temp,result;
  if (length==1)
    return ptr[0];
  n = length-1;
  temp = (char*)malloc(n*sizeof(char));
  if (temp)
  {
    for (i=0;i<n;i++)
    {
      temp[i]=mix(ptr[i],ptr[i+1]);
      printf("%c",temp[i]);
    }
    printf("\n");
    for (i=n-1;i>0;i--)
    {
      for (j=0;j<i;j++)
      {
        temp[j]=mix(temp[j],temp[j+1]);
        printf("%c",temp[j]);
      }
      printf("\n");

    }

    result = temp[0];
    free(temp);
  }
  return result;
}
/*
char recursiveMix(const char *ptr, int length)
{
  if ((length%2==0) && (length/2>2))
  {
    length = length/2;

    return mix(recursiveMix(ptr,length),recursiveMix(&ptr[length],length));
  }
  else
    return defaultMix((const char*)ptr,length);
}
*/
char layerMix(const char *row)
{
  int i,n;
  char *temp;
  int rgbCount1[3]={0,0,0};
  int rgbCount2[3]={0,0,0};
  char result[3]={'R','G','B'};
  n = strlen(row);
  temp = (char*)malloc((n-1)*sizeof(char));
  if (temp)
  {
    for (i=0;i<n;i++)
    {
      if (row[i]=='R') rgbCount1[0]++;
      if (row[i]=='G') rgbCount1[1]++;
      if (row[i]=='B') rgbCount1[2]++;
      if (i>0)
      {
        temp[i-1]=mix(row[i-1],row[i]);
        if (temp[i-1]=='R') rgbCount2[0]++;
        if (temp[i-1]=='G') rgbCount2[1]++;
        if (temp[i-1]=='B') rgbCount2[2]++;
      }
    }
    free(temp);
    for (i=0;i<3;i++)
    {
      /*
      if (rgbCount2[i]>rgbCount1[i])
      {
        printf("%c incremented\n",result[i]);
      }
      if (rgbCount2[i]<rgbCount1[i])
      {
        printf("%c decremented\n",result[i]);
      }
      if (rgbCount2[i]==rgbCount1[i])
      {
        printf("%c stable\n",result[i]);
      }
      */
      printf("%c passing from %i to %i\n",result[i],rgbCount1[i],rgbCount2[i]);
    }
  }
  return 'R';
}


char straightMix(const char *row)
{
  int i;
  char res;
  int length= strlen(row);
  res=row[0];
  for (i=1;i<length;i++)
  {
    res = mix(row[i-1],row[i]);
  }
  return res;
}
/*
char _triangle(const char *row)
{
  int length;
  length = strlen(row);
  if (length<1)
    return 0;
  if (length==1)
    return *row;
  if (length==2)
    return mix(row[0],row[1]);
  return recursiveMix(row,length);
}
*/


static char getInt(char c)
{
  if (c=='R') return 0;
  if (c=='G') return 1;
  if (c=='B') return 2;
  return -1;
}

#define MAX_LENGTH 13
static void printSequence(unsigned int n)
{
  unsigned i,j;
  unsigned p;
  unsigned* power;
  int bracketCount;
  char* buf;
  if (n==0)
  {
    printf("ERROR: size cannot be zero\n");
    return;
  }
  if (n>MAX_LENGTH)
  {
    printf("ERROR: size is too large\n");
    return;
  }
  buf = (char*)malloc(MAX_LENGTH*sizeof(char));
  if (buf==NULL)
  {
    printf("ERROR: malloc failed\n");
    return;
  }
  power = (unsigned*)malloc(n*sizeof(unsigned));
  if (power==NULL)
  {
    printf("ERROR: malloc failed\n");
    free(buf);
    return;
  }

  for (i=0,p=1;i<n;i++)
  {
    p = p*3;
    power[i]=p;
  }
  printf("static const int mixOrder=%d;\n",n);
  printf("static char mix%d",n);
  for (i=0;i<n;i++) printf("[3]");
  printf("=");
  for (i=0;i<p;i++)
  {
    printOpenBrackets(i,n,power);
    printfBase3(i,buf,n);
    printf("'%c'",defaultMix(buf,n));
    printClosedBrackets(i,n,power);
  }
  free(buf);
  free(power);
  printf("static char getMix(char* ptr)\n{\n");
  printf("  return mix%d",n);
  for (i=0;i<n;i++)
  {
    printf("[getInt(ptr[%i])]",i);
  }
  printf(";\n}\n");
}



int reverseAndMix(char* ptr,int length)
{
  int i;
  int m = length/2;
  for (i=0;i<m;i++)
  {
    ptr[i]=mix(ptr[i],ptr[length-1-i]);
  }
  if (length%2)
  {
    ptr[m+1]=0;
    return m+1;
  }
  else
  {
    ptr[m]=0;
    return m;
  }

}
static char mixFourPowerOf3(char* , unsigned );
void generate(int N)
{
  int i;
  long power;
  int count;
  char m,l,r,q1,q2,q3,q4;
  char buf[MAX_STRING_LENGTH+1];
  struct sequence_t *seqList = NULL;
  if (N<2)
    return;
  if (N>MAX_STRING_LENGTH)
    return;
  for (i=0,power=1;i<N;i++)
  {
    power = power*3;
  }
  buf[N]=0;
  for (i=0,count=0;i<power;i++)
  {
    printfBase3(i,buf,N);

    if (!alreadyAdded(seqList,buf,N))
    {
      seqList = addSequence(seqList,buf,N);
      if (defaultMix(buf,N)!=mixFourPowerOf3(buf,N))
        printf("Wrong\n");

      count++;
    }
  }
  deleteList(seqList);
  printf("A total of %i sequences\n",count);
}

static char mixPowerOf3(char* ptr, unsigned length)
{
  char temp[3];

  if (length==3) return defaultMix(ptr,length);
  length = length/3;
  temp[0] = mixPowerOf3(ptr,length);
  temp[1] = mixPowerOf3(&ptr[length],length);
  temp[2] = mixPowerOf3(&ptr[2*length],length);
  return defaultMix(temp,3);
}

static char mixPowerOf3PlusOne(char* ptr, unsigned length)
{
  return mix(ptr[0],ptr[length-1]);
}



#define MAX_POW3_NUM  20
static const unsigned long pow3[MAX_POW3_NUM] = {1,3,9,27,81,243,729,2187,6561,19683,
                                       59049,177147,531441,1594323,4782969,
                                       14348907,43046721,129140163,387420489,
                                       1162261467};

enum eLength_type
{
  ePowerOf3,
  ePowerOf3PlusOne,
  eMultipleOfPowerOf3,
  eGeneric,
  eInvalid
};


static enum eLength_type getLengthType(unsigned long length)
{
  int i;
  for (i=0;i<MAX_POW3_NUM;i++)
  {
    if (length<pow3[i])
      break;
  }
  if (i==MAX_POW3_NUM)
    return eInvalid;
  if (i==0)
    return eInvalid;
  i--;
  if (length==pow3[i])
    return ePowerOf3;
  if (length == pow3[i]+1)
    ePowerOf3PlusOne;
  for (;i>0;i--)
  {
    if (length%pow3[i]==0)
      return eMultipleOfPowerOf3;
  }
  return eGeneric;
}
static char lengthBasedMix(char* , unsigned );
static char mixMultipleOfPowerOf3(char* ptr, unsigned length)
{
  unsigned i,l;
  char* temp,result;
  for (l = length;;)
  {
    if (l%3)
      break;
    else
      l=l/3;
  }

  temp = (char*)malloc(l*sizeof(char));
  if (temp==NULL)
  {
    printf("ERROR: malloc\n");
    return 0;
  }
  length = length/l;
  for (i=0;i<l;i++)
  {
    temp[i] = mixPowerOf3(&ptr[i*length],length);
  }
  result = lengthBasedMix(temp,l);
  free(temp);
  return result;
}


static char lengthBasedMix(char* ptr, unsigned length)
{
  unsigned i;
  char *temp;
  char result;
  enum eLength_type t;
  if (length==2)
    return mix(ptr[0],ptr[1]);
  t = getLengthType(length);
  printf("L=%d, type=%i\n",length,t);
  switch (t)
  {
    case ePowerOf3:return mixPowerOf3(ptr,length);
    case ePowerOf3PlusOne:return mixPowerOf3PlusOne(ptr,length);
    case eMultipleOfPowerOf3:return mixMultipleOfPowerOf3(ptr,length);
    case eGeneric:
      if (length<4)
        return defaultMix(ptr,length);
      length--;
      temp = (char*)malloc(length*sizeof(char));
      if (temp==NULL)
      {
        printf("ERROR: malloc\n");
        return 0;
      }
      for (i=0;i<length;i++)
      {
        temp[i]=mix(ptr[i],ptr[i+1]);
      }
      result = lengthBasedMix(temp,length);
      free(temp);
      return result;
    break;
    case eInvalid:
      printf("ERROR: sequence too large\n");
      return 0;
    default:return 0;
  }
  return 0;
}

char myTriangle(const char* row)
{
  unsigned n;
  if (row==NULL)
    return 0;
  n = strlen(row);
  if (n<1)
    return 0;
  if (n==1)
    return row[0];
  if (n==2)
    return mix(row[0],row[1]);
  return lengthBasedMix((char*)row,n);
}

int main(int argc, char* argv[])
{
  int i,length;
  int n;

  const char* test[]={"GRGBGGRRGBGBGBGRRGGBBRRBBBGGGBRRRBRGGGGRRRBBGBBBRBGGBBRBBGGRRBRBBGRGBRRRRBRBBRBGRRBBRRBBGRRBRGGGRRBRGBGBRBBRRGBGBBGRBGBGRRGRBRBRGRGBRRBGBBBGRBBRBRRGBGRRBBGBRGBBGBBGBGGBGRGBBRRBGRGGBBGBBRGBGBGRGBBRRRRBGGGBBBGGGRRRRBRBRRBBBGBGRBBBGRBRBGRRGBBBRBRGBGGBGRGGRGBRBGRRBBGRBBRRBRRBBRGBBRBRGGBGRGBBGRRGRBGBBBRGBRRRGRRGRBBGGRRBBRBRRGRGGBGRBGGBBBRBBRGRGGBBGRBGRBBGRBGGBBBBBRBBRRGRGBGBBRBRGGGBGGGBGBGGBRRGGGBBGRRRGGRRRRRGBRGGBRRGRBRBRRBBGGGRBBGRRBGGBRRGRBRRBBGBBGBBRGGBBRRBBBRGBBBGBRRRBGRBGBGRGGBBRBGRBBRRGRBRRBBBRRRRBRRRRBRBRRGGBBBRBBGGRRRGBRGRGBGRRBGGGBGRGBBRRBGRBBBBRRGGGGGBRRGGBRGBRBRGBBBRGGRRGRRRGBGBRRBGGRRGGGGBGGGGGRGRBBGBRBBGBGGRGBBRBBBGGGGRRBGBGRRRRGRRGBRRRBGRGRRBGBGRBRRBRBBGRBRGGRBRGBGBBRBGGRRBRBRBBRBBRBBRBBBGRGBGBRGBRGRBBGBRRBRRRGRRGBGRBRBRBGBGBGRRRGRBBRRRRBGGRBBGBRGRBGGBBRRGBGRRBRRRGGRBRBGGBRRBGGBGRRRRBRRGBRGBGGBBRRBGRRRRGRRRBRBRBBRGGGRRGBRBGRBRGBGGBBBGRRGBGRRRRBBGRBBBBRBGRGGGRRGRRGGGBRGRGRGGBGRRBRRGGRRGGBGRRRGGGRRRGBRBRBBBGRRRGGBBGRBRBRGRRRRBGRRBRRBRGBRRRGGGBRBRGGGBGRBBRRBGGBGBBGRGGRGBBBGGGRBBGGGRBBRBBBGGGRGBBBRRBRRRRBGGBBBBGRBRBGBRRGGBGBBGBBBRRRRGBBRRGBBBGBBGRBGBRRBBRGGRGGRBBGGBRGRBBBBRBBGGBGRGGRGBGRRBBGGBBRGGBGRBGRBGRGBRBRGGRRBBGBBRBGBBBGRBBGGGBGRBRRRRBBBRRGRGBRBGGBGGRBRGGBBGGBGBGBRRBBRBGRGRRRBRRRGGRRRBRBGBRBBGRBBBBBBRGGGBGRRRBRBBRBBRGGRBGRGGBRGBGRRBGBBGRGBBGGRGRBBBGGBGGRBBGBBRRBRRBBGRRGBGBBRBRGBGBGBRRRRBBBBRBBRBBBBGRBBBBGBBBBBGGBBGRRGRRRGBRGRRGBGGBGBBRGBBGBGRBGBBBGRBBGRGBRGGBRRRBBBRGBBGBGGGRGGBRGBGRBBGBGBRGBRRBRRBBRRBBBGBRRBBBGRGBRBGGGBBBRRBGBGBRGGBRRBBGGBRRRGBRGBGRBGRRBBGGGRGRRGGRRGGBRBRRBBRRBBGBGGBGBGRRRBRRGBGGRRBRBBGBBBGRGBBRBBBGRRGGRBGGRRGRRRBGRGRRGGRBBBGGBGRGBBBBGBGGBRRRGRGGGBBBGRRGRBRRRRGBBGBGRGRRGGRBBGGRRBGBRBGRGGGGGRGRBGBBRRBGBRBGBGBGGRRGBRRGGGRGRGBBRBBGBRRBRBGRBGGRBBRRRRGBBBGBGRBBRBRRRGGGGBGGRRBRGBGBRBBBBRBGGGGBGBBGGRRBGBGGGGBRGRBGGBRRRRBGRGGGGBGBRBBGBGRRRRGGBBRGBBBBBBBBGRBBBRBRBBGGGBRGGBGRGGBRGGRGGRGBRRBRGBGRBBRRRGBGRRBRRGGGBGRGBRGRRGGBRBRRBGRBBGGGGRGBBBBBBRGGRRBGBRGGBGGBGRBRGGBRGGRGGRGGRRRBRRGGRBBGGRRRRBGGRGBRRRBBGRRBGGGBGBRRBBGBRGBGGGRRRRRGGBRBRRGBGGGGGBGBGBBBGBGBGBRBBRGRRGRGBGRGRBBBBGGRRRRBBBBGGRGRGBGBRGBRRBBGBGGGRBRGRGGBRGBGGGBRGRRBBRRBBBGRGBBGBBGBRBRRGRBRGGGBGBRGBRBBRRRGGRGGRBGGBBBRBRRGGBGGGBBGBGBBRBRBBGRRGGBRGBGGBRRBBBRBGRGRBRRRRGBRRBGBBRRRGGRRGRRBBRBRGRGGGGBBBGBRGGRRBGBRBRBBRBBRGGRRBBBRRGBRBRBGBBRGRRRRRBRRBRRGGGGGRRBGBRBBGGGRGGGBGGRGGGBBBRRGGRRBGRRGGBGBBBBRGGRRGGBBRGBBGGBRBBBRRRBGRGGRGRRRRGGGRGGGRGGRBRRGGGBGGBGBGRBRBGRBBRRRGGBBBRBBBGGRBGBGGGGRBGRGBBRBBRRGBBRBRRBBBGRBRRRGBBBGGBRRGRRGGGBGGRGBGGGGBBRRRGBBGGGRBBGRRRRBGBGRRRBBBGGBGGRGGRBBBGRGRGBRBBGGRRBGGBBGRRRRBGGGBRRBGGRBRRRRGBGGRGRBRBRGRGGRGGGGBBRBGGGGBBGRRRBRGRBBBRGRGRGBGRGGRGGGRRRRBGGRBGRGGRGGGRRRRGRRBBBRGRBRRBGRGBGRRBRBGGGBGGRBRBRRBBGGBRGRRRGGRRBGBBGGGRGRGBRBGGRRRBBGBGBBBRRRGRGBRBRBRBBGBGBRBRBBBBGBRGGBBBRGGBRBBRRRRRBRGGRRGRGGBBRRRBRGBGBGGBGRRGRGBGGRRRGBRRRRBBGGGBBGGGBBGGGBRBGBRBGGRBGGBBBBGGRRGRGRBBRRGGGGGBGGBRRRRGBRGBBRGGRBGRBBBRRRBGGRRRRRRRGRRGRBRGBBBRGGRBRBRGRBBGRGRGBRGRBBGRGBGGGRBRRRBRBBBRRBGRRBBBGGRRGBRBBBGGRRGRRGBRGGRGRRBGBGGGGBGBBRGGRGBRGBBBGGBBRGBBGBRGBRRRBBBRBGGRBBBGGGGBRGBRRBBBBGGGGBGGBGBRBGRRGBBRGRBBBBRRBRBGGGRRGGRGBBGBGGRBBBBGRBGGBGGBGGGGRGBGBBBBRGBGGRBRRBGBBBRBGGBGBRRRGBBRRBRRGRBRGGRBGBGGRGRBRBRBBGGGGRGBRBBBBBBGGRGRGRGGGBRGBBGGRBBBRGGBGGBGGBRRRGRGGBBRGGBRGBBBBBBGGGRRGBGRBBGRGGGGGBGBRBRGGRGRBRBGRBGBRRRRBGRBBRRRBBRRGGBRGRBGBGBBGGBBGBBBRGGRGGGRRBRRRBRGBBRBGRBRGGBRGBBGRGBGBRBGBRGRRBBRBBRGRRGGGGRRRRBBBBRGRGRRGGGBGGRGGRBBRGGRBGRRBRBGBGRRBGGRRBRBGRGRBRBBGRBGBRBBGGGGBGGBRRGGGGGBRRBBGGGGRBBRRGBGGRGGBRGRGBBBGGBGGRRGBRBBRGBRGBRBBGGRGBGRBGRBBRRBRBRRRBRGRBBBRBGRGRRGRGGGBRRRRGBGGRGBBBRRRGRRGBRRRBBBRRRGRGBGRGRRBRRGRBBRRRGGRBBGGGRBRGGGBRGGBGBGBBRGGRGGRRRGRRRBBRBBBGRBBGGBGRGGRBBBRBGGRBRRBGRBGBGGGBBGGRRBBBBRGGBGRGRRRGGGBGRGBBRRBRGGGBBRBGRGRGGGBBBGRBBRRBGRBBGBBRBGGGBRRGBRBRBGBRBRBBRRRRGBBBRRRBBGGBBGRBGBRBBRBBGGRRGRRBRRBGGRRRBGGBRGGBBGGBBRBGBBGRBBRGBRBBRGRRRGRGRGGRRRBGGGRRGBRGGGBGBBRRRBGRRGBRBRRGRRRGBRGGBRBGGRRGBBBRGRGGBGRBGGGRBGGBGGRGGBRRBBBBGGRRBBBGGBBRBRRGBRGGBGGRGBGBGRGRBRGRRGGGGGBRBGBBBRGGBBBGRRRBBBRBRBBRRBBBRRRRGRBRGGGGGRRGGRGRRBGGGRBBRRBGRBBGRBBBRRGGGGRBBBGRGBBBRBBBRGGRBRGBBGBRGRBRBRRGRGRGGBGRBGBBRGRBGBRGRBGBGGBRBRRBBGGBRRRGBRGBGBRBGRGBRGGGRBRRBGRBBBGBBBGGBRGRRBGGRBGGGRRBRGRRBRBGBBBGGRRGGRGGBBRGRBBGRRGRBGRBBRGGRRGGGBBRRBGRBBGBBGBBBRRBBRBBGGRGGBRBRRRRRBGRBBRGGRBBBBGGRGGRBBGRBBGRGGRGGBBGBGRBBBGGBRRGBGGGGBRGRBGGGGRRGGBGBBGGRBGBRGRBRGBGBBBBBGGRBGGBBRGBGBBGBRGBBBBBGBGGBGGGBBGRBRBBGRRBBBRGRRGBBGRGRGGBRBGRRGRRBBRRRRGBRBGRBGGBBGGRRBRGBRBBGRRRGGGGGBBRBGGGBBGBGRRBRGRRGBGRRGGBBRRBRBBRBGBGGGGRBGBRGRRBRGGGRBRRRBBGBBGGBGRGRBGBBGBRBGRRBGBRGRGGBGRBBBRGGGBBBRGGBBGGRGRRGBGRBBBRRRBBRRGGRRGBBGGGRBGGGGGRGBRGBRBRRGRGRRRGRBGRRBRGBGBRRGGBGBGRBGGRRRGRRRBGBRBBRBRBGRRBGBBRGRBBGGRBGRRBRRBBGGBBGRBRRBRBBBRBBBBBGBGGBBRRRBRBGBBRBGRRBRRBRGBRGGBBBGRBRBRGBRGBRGBRRGBBBBRRGBGBGGBRBRBRRRBBGGBBRBRGGBGRGGRBGBBRRBGRRGBRBGRGGRRGRRRGGBGBGRRRBRRRBBRRGBGGBBRGRGRRGGGRGRRBRGRRBGRRGGRRBBBBBBGBRGBBRGRGGGGBRGRBBGBGBGGBRGBBRRBRBGRBRGGGBRRBBRGBBBGBRRBRBBRBBBGBGBBGRGRBBBBGRGRRRBBRRBGRGBBGBGGRRRBRBRRGBBBRGGRGRRRRRBRGBGRGBBRGRBGGRRBRBRGGGGGGBGRBRGGRRRBGRBBRBGGGGBGBBRRGBGRBRRBBRRBRGBBGBGBBRGGBRBGRGRGGBBRGRBRRRRBRRGGBRRBGRRRRGRBBRRRBBGRRGGGBBRBRRGRRBGBBGRGRRRBRGRGBGBRBGGBGRGBRBBGRRRBRGGRBBGRGGBRRBRRGBRBRBBRBGBBRRRRBBGGBBBGBBGRGBRRBGBRGBGGRGGGBBBGGBRGGRBGRGGGGRGGBGBRRGGGRRGRRRBBRRRBGGGGBRRGGBRRGRGBGRGBGBBBGBGGBRGGGRRGGRBRRRRGRBRBBBBGGBGRGRBBGGRBGBBRBBRGRGBGRRGGRRRBRGRBRRGGGBBGGGBBGRRGGBRRRBGGRBGRBBRBBGGGBGRRRRBBGRRRRGRGGBRBBBRGGGGGRBRRGGGGBGRRBBGRGRBRBRBBBGGRBRGRGRGRBRBGBRBBRRRBRRRGRBGRGGGGGGBRGGRRGRGGGGGGBGRRGRBRGGGRBBBBRBBBRRBBGGRBBGRRGGGRRRRBBGBBBBBRGBRGRBGGBRRBGGBRGRGGGGGGGGGRGRRBBRBGGRBRRRRRGRRBRBGRGRGRBBRGRGRRRRGBBGRRBRGRRBGBGRBRGGRGGGBGGRGGBGRGRGGBGRRRRBRBRRGBGBGBGGGBBRGGGBBGRBGBRBBGGBGBRBGGBBGGGBGGGBBBGRBBRRGRRBBBBRGRRGBRGBBRBRGRRRGBRRGRGRGBBRGBBRRBGBRRGBGGRBGRBRBGRRBRGBBGRGRBBRBGRBBBBRGBRRRRGBGBRBBBGGGBRGBRBGBRBBRGRGBRRRGBRRGGRGGBRBGBGRRGBBBBBBGBBGRBBGGRBRGRGRBRBGRBBRRBBBGBBRBBGRGRBRRBRRBRGRGGBGRGGGGGRRRRGRBRRGGBGRBRGBGBRBRBGGRRBBGRRBGBBRBRBBBGRBBGBRGBRGBGRBGRRRGGRBRRRGRRGGRGRBRRGGBGRGRBGBBBGRRGRBBBRRBGGRRBRGBGRBRGGRRRGRBBGGGBRGGGRGRGBRGRGGBBGBRBGGRRBGRRBGBRGGGGGGRGBGGGGRRBRRGGBRBGGBBRGBRRBBGRRGGRGRGBGBBGBGGRGRGBRRRBGGBRRGRGRBGBBRBRBGGRGRRBGGRBRRBGBGGBRBBRGRRRBBRGBBBRRBBBBBGBGGRRRBRRGBGBGGRRBRBBRBBRGBRRRBRGRGBRRBRBBRBGBBGGRGRGRRBRRGGRRBBGGGBBRGBRGRGRBRRGBGRRBRRBGBRBBBGGRRGRBGBRGRBGBBBGRRGBGRBBRBBRBRGBBRGGGRRRGBGGBBBBBBRRBRGRGRRRBGGBGBGRRGRBGRGRBGGBRGGRGBRBRRGBRBGGGGRBBRBBGRBRRRRGBGBGGRGGBBGBGRGRBGRBRGGGBGBBRRGBBGRRGRBRRGBRRGGBBRGRGRBRRBRRBGBBBGRGBBBBGBBGRBRGBRGRGGRGRGBBRBBRGBBRBGRRGGGBRBGBBRRBBGRBRGRRRBGBBGRGRRBGGGGBRBGGGBRRGGRGBRBRGGBGBBRBGBGBGBRGRBRGBRBRRBBBGGRBGRRRGGGBRRBBRBRRBBBGRGBRBGRRRGRGGGRRBGBRGBBGBRRGBBRGBBGGGBBBGRGGGGGGRGGBGGGRGBBBBBRBRBGGBRGGRRBBBGRRRBBGRGGBGGBGBBGBGRRGGBRBBRBBGRRBRGRGBRGBBRGGRBRGBGGGRBGRBRRBGGGRBRGBGBGRRBBRRBGBGRGBBRRRBGBRBGRGBBGRBRGBRGBRRBGRRRBRGRGRGRGGBRRBBGRBBGBRRRGGBRBBGGRBBGBRBRBRRBBGGBGGBRGBRGGRGRGRRGBBGBGGGRGBRRRBGGRGRRGGGRBRGRGGBGBGGRRBRGGGRRRBBBRRBGBGBBBGRRRRRBBBRBGBGRRGGGRBRGBRRGGRGRBGBRBRRGBBGGGBBGBGRRRGBRGRBRRGBRRBGBBBGBGRRBBRBBGBRBBBRRBRBRGBRBGBBGBGGRGGGBGRGGRBGBGBGGRRBRRRBBRRRRGBRRRBBBRGGGGRRRRBBGRBGRRGBGGRGRBRRRBRGRBBBRRRBGRGRRGGBGBGRBRGBBBRGBGBRRBBBRBBBBRBGBGRGGBBRBBRRGGGRBGRGRRGGRRGBGGRGBGBBGBBRBGGRBBBRGRGRGRGGRGGBBRRRGBBRBBGGRBBGRBGBBRBRRBBRRGBRGBRRBBGBBRGRRGGGRRGRRGGRRGGGBGBGGRBGRRGRGBGBGGGBGBBBGGBBBGBBRGRBGRRBBGRRGRRRGBRRBRBGGRGGBRRBBGGGRGBBRRBRRGGBGGRRRBBGRGGBBBBBBGGBGRGBBGBRRGRGRRBRRBRBGBGGGGGGRBGBGRGRBBGRGGBGBBRGGGRRRBGBGBGBBBGRRRGRBRRRBRBBBRGRGGGBRBGBBRBBRGRGBBBGRBRBGRGRRBBBGRGRGRRRGRRBBBRGGBGBBGGRGGGBGGGRGRGRRGBGGBRGGRRRRBBGRBBBRGGGBRBGRRGGBRBGGGRRBBBRGBBBGGBBRBGBBGGGBGBGGBRRRGBGRGGGRGGRBBBBGGBGRRBRGGBGBBBRGGGBBRBGGRGGRGGGRRRGBBBGBGRBRRBRGBBBBGGBRBGRGBBBRRGRRRGBGRGRRBRBGRBRBRRRRGRRGRBBGGBBGGGGGGBBRBRGRRBRGRRBBGBRBRBGGBRRGBBRRGGGGBBBBRBGGRGRBGGBGGRRGGBRGGGBRBGBBRGBGBRBRBRBGBGRRRGGGGGBBRBRRGGRGBRGBRRBGGGRRGGGBRRRGRGBRGBGBGBGGBBRGGGBBBRRGGBRBBBRBRBRBRRGGBRRBRBGBRGGRGBRRGGBGRGGGGBRBBBBBRRBGBRRRGBBRBRBRGGBBRGGRGBBGBBGBRGGRBBBBBGBGGGBRGRBBGGBRGRBRBRGBGRRGRBRRGRBRRGRBBGGRRGGBGRBRGGGBBBGRBBRRRBGGGGRGRGBRRGRBBRGRBBGBBRBGRBBGBRBBBRGGBGBRRRBRGGGRGBRRGBGGRRRRGBRBBGRGGRBGRRGGGGBRGRRBBRRRGGBGRBGRBBRRBRGRRGGRRGGGGBGBRBRBGBGBBBGGGGBRBGRGBRGBGRBGBRGGRGRGGGBRRRBGBBBGRRBGGGGRBRGRGBGBGBGRRRGGRRRRRBBRRBBGBGBBBRBGGRGRBBRRRGBGBBBBBBRRBRBBBGBGBGRGRGGRGGBBBGGBGGGGRBGGRGRBRBRGBGBRRBRGGBGGBRGRGRBRRGGRRBBGRRBRBRRRBGBRBGBGBGBGBGGBRRRRRBRGRBGRBGGBRGRBBRGBGRGRBRRRGRGBRGRGGBBGRGGGBBGRBBBBRGRRBGRGBBRRGGBRRBBGRGBBRGRRGGBBBRRBBGRGGGGBRGRGRRRRGRGBBBBRRBRGRGRBRBRBGRGRBBGRRBGGRRGBRGGRGBBGGGRBRGGBBGBBRBBGBGRBBBBBRRRBGRRBBGBBRRBRBRRRRRBBGBBGBGRRRBBGRBGBGGBBRBRBBRBBRBGBBGGBRBRRGBBBRGGGRGGRGGBRGRGBBRRBBGBBRBRRBRBBGBGGRBBGGRRRRGGRGGGGRGGGRBGRBBRBGGRBGGBRGBBGGRBRBRBBGRRBRRRBBRBGBGGRBRBRRGBGGBBGRGRBBGBBGRRGGBRRRBGRRRRGGRBRRBGRRGRRGBRBRRBGGBBBBGRRBGGGBGBBGGRBRRRGGGBGBBGGBRGBBGBBBGGBBRGGBBGRGGBBBBGRBBGBGBGRGGBGBRRBBRGGBBBGRRRGRRGRRBBGBGBGBBBGGGRRBBGBGBGRBBGBBBBGBBBBRBGBRGGGBRGBBRBBRRBBBRRRRBGRRGRRBBGBRBRGRBRGRRRGRBGGRGGGBRGBGBRGBGRGBGBBGRRBGRGGRRRRBBBBBBBBBBRBGGRRRRBBRGBBGGBRGBRGBGGGRRGRRBRGGRBGGGGBRGGBBGBBGRRRBRBRRBGRGGBRRGBGGGGGBGRRBRBRBRGGRBBGGRBRBBGBRRGGBRRRGGRGRBBBRGRBGBRRRRRRBGRGBBBBRRBGBBRRBRBRBBBRRRRGGGBRRGBBRBGRRRRRRRRRGBGGRRGGGBBBGRRGGRBGRRRRBGBRBBGGBBBRBBGGBGGBGBGRRRRRBRGBGRBRGGBGGRGBRRRBGBGGBGBBGBRRBBRGRRRBBBRGBGRBGRRRRBBBRBBRGBGBBBRRRGBBGRRGGRBRBRRBRRBBRGBGBRGBBRRBGRRRRRBGBBBGRBGRRGBRRBRRRGBRGRGGRGGRBGBGRGRGGBRRGBRGBGBRGBRRBGGBRRRRGBBRGGGRRBRBBGGBGGBBGRRRBBGRBGRGBRGGGGBBRBGRBRRGBBGGGGGGRBGRGBRGRBBBRBBBBGRBBGRBGGRRGBGBBRRGBRRRBBBGBBGBRBBRGRBGBRGGGRGRRBBRRRGRBGGRRRBRGGGBBGRRRRGGRRBGBGGBGBRGGBGGGGGBGRBRRRGRRGGGGRBGBGGGGGBBBBRRRBBGRBRRRBGGRBBBRGGBBBRRGRRGBRGGRGBGRRBGRRBRBRRBBGBBGBRRBGGRBRGBGGGBBRGRRGRRBBRGRBGBBBRRGGRGBBBRRRGRBBRRGBGRGBBBRRBRRBRBBGGGRRRBRGBRRGGBRRBGRGRRRRGRRBRRGGGBBGGRBBGGRBRRBRBBRRGRGRGBBGBRRRGBRBRRGBGBGBBGGBGGRRBGRRGRRRGGGBBBBRRGBGGRBGBRGGGGBGRBBGBRBGBGRGGRBGRGRGBBRGRGBBBGRRBGBGGGRRRBBBRGRRRGBBBRGBGGBBRRBRGBRRGRGBRBGGGBGBGGBRGGRRRRBGGRBRRBGGRRGGRRRGRBGBRGRBBRGRGRGRRRGRRRRBGBRGBGRRRBBBRBBRGRRRGBGBGBGGRGRGGGRRBBGGGGRBBRRRGGRRRBBGGGRBRGGGGRBRBGBGRRRBGGRBBGBBRBGBBBBBGGGBBRGGBRRBGRRBBRBGBBGRBRBGBBGRBBGGRBRRBGRGBRGBBRGBRBBRBRBBRRRBRGGGRBGGRBBRRGRBBGGRGBGGBRGBBGBBGGGBRRRGBRBRBRRBGRBRBGGBRBGBGGBBBGBRBRRBGBBRRGRBGRBGRGRRRGBBGGRGGRRRRRBBRRRRGGBRBBGBRGRGRBRGGGRBGGBRGRBBRRBBBBBBGRBGGBBGBRGRBBGRRGRGGRGBBRGGRRGGRGRBGBGRBRGGBBRBBGGRBBRBRGGRRBGGGGGBGRRGRGGBBGBBRRBRRRBRBRRRRBGGGBRRRGGGGRRGGRRRRBRRRRGRGBGBBBRRRBGRRGBBGRRGGRGBGBGBBBBBBRGGRBRRGGBRRBBBBRRGGBGBGBGBBRGGGBGBGGRGRBBGGGGBBGRGRBRBBBGBRBGRBBRBGRRRGBBRGRBGBGBRGBBBBGGGGRGGRGRBBGBGGGBBBBRGGRGRGBBRRGGGBRRRGGRBBRRRRRGBRGGBRRBGBBBRGBRGBRGBBBGBRBGRRBBGGGRGRGBBGRRRBGBGGGRGGBBBRRBRBBBRBBBBRBBRBRRBGRGGGBRRRBBRBBGGRRRBBRBGRGGGRBRGRGRBBGRBRRBGGGRGGRRGGRRBGBRBBRGBRBBRRRBBGBRBRGRBRGRGGGGGRGRRRBRGBRBRGGRRGGBBRGGRRGGBRGGBRBRRRRBRBGRRRBRBRGGRRBRRBRRRGGBGBRRBBRRGRGGGRRGGBRGBGRBGRRGBBBGBBBBGRBBGGBBGBGBGBBGRBRBRGRBBBGGRGBGBGBRBGRBGBGRBRGRRBBRGRRGGBRGGBRGGBGGGBRRBRRGGGBBGGRRRGGGGBBRBBGGRRBBRRRRGGBBRBBBGRRGBGRGRBGRRRGRRGRGBRGGBBRRGRRRRRRRBRGRGBGGBRBRBRGBBGRBRGBBBRRRRRRRBGRGRBBRRBGRBRRGBRGBBRBGGRGBGGBRBGGRGGGBGRRBBRGGGRBGGGBRGGBRRRGRGGGBRGBBGBGRRRBGRGBBRRBBGBRBBGRRRBGGRRRBRBRRBRGGBBRBBRBGRBRGBGGBGRGGGBRGBGBRGGGGGBGRRGBRGBGGGGGBBGGGRRBRGBRGGGRRGBGGGRBRRBGBRRBBGBGBBGRGGGBBRGRGRGBGGBGBGRGBBBBRGRRGBGBRBRRBGRRGBRRRRBRBGBBRBBGGRRBRGBGGRRRGGBBGRRBRGRGBGRRRBGRBGBRGBBBBRRGGRBRGBRBGGRGBGGGRGGRRGGGBRGGGRRRRBGBBGRBGGRRRRBRBGGBRRGBGRGRRBGBBBBRBBBRGRGGGGBRBGRRGBRRBRRGBBRBBBRGRRGGRBRRGBRBRGBBRRGGRBBRBRRGRRRRRBBBBRBGRBRGGRBBGRRBBRRGGRRRBGGBGGBGBGRBBGGRGRRRGBBRRRRBGGBGRRRBBRRBBRBGBGBGGRBRBGGRRBBGRBRGGRGRGBRBGRRRGRGGGRGGRRGRBBBGGRRBRGGRGBBBRRRBGBGBRRGGBRBGBBRGBGGGBRBGBBGRBBRGBBGBBRBGRGGRBGGGBRRRGBBGGGBGGBRRBBRGBBGRBRRGGRRBGGRRRBBRGGBBGBBRGRBBRRBBRGGRBBRGGRGGBRBBBGGRGBGGRGRRBRGGBBGGBBRRBBRBGRGRBGBRRRGRBBRBRBRBBBBBGRGRBBRGBBRBRBRRRBGRBGRBGRBGBGGRGRGBBGRRGRBBRBRBBGRBGRGRRRGRRRRBGBGGRRGRRBBBGRGGGGRBGBRBGBBGRRRBBRRRRRRGBRGGGBGRGBGRBGBGGBBGBRRBGGRGGGGGGBRRRGGBRBRRRBGGRRRBBGRRRRRBBBGBBGBRRRRRBRGGRRBRBGGGBGBRBRRGRBGRRGRGGGBBGRRRBRRGGBBGGBGGGBRGGGGBRRRBGRBGGBGRBBGGBGRRGGBBGRRBBRBGGRRRRRGBBBRBRBRBRRRBRRBGGGGBGGRRBRRBRBBRBRBBRGBRBGGBGRGGGRRRBRRGGGBBGBBRBBGRRRBGBRRBRRRRGRGRRBRBGBGBBGBRRGRBRBRBBGGGBGBRBRGRBBBGBRRGGGGRBBRRBGRBBBGRBRRGGBBBGGRRRGRBRGBRGRGGGBGBGBBGRBRGRRRGBGRBRRRGGRGGGRBBBRBBBGRRBGGBGBGBGGBBBBRBRGRGBRGBRGGRRRRRBGBGGBGRGRBGRBGRGGBGGRGBBRBRGRRRBGBBGRBBBBGBGBRRGRGRRRBGGBBRRBRRGGBRBGRGRBRRRGRGGRRRGBGRRRRRRGGRBRRBRGRGBBGBGBGRBGGGBBGRRGRRRRRRRBRGRRRBRGBBGGRGRGBRGRRGBBGRBRGRBGBRBRRRGRRRGRBBBBRRRGGRRRGRRBRRRRBBRRRBRGRBGRBGBBGRGRGBGRBBBRRRGBRBBGBRBBBBRBGRRRGGRRGBRGBRGRRRRRRRBBRRBRRBRGRRGGRRBBBBRBBRBRGBGGBGRRGRGGBGGRRBBGRBRGGGRBGRBRBGGBGBRBBGBRRRRGRBBBBRRBBRGGRGBGGGGBGGBGBGGRBBBGRBRBRRGRRRBBBGRRGGBRRGGRGGRGGBBGRBGRBRRGGBRRBGGGRGGRRRRBBGGGBRBBRGRRBGGRGBGRRRGGGRBBGRBRBRBGRBGGGGBRBGGRGRBBRGBBBGBGBGBGGBRBBBBRRBBRRGRBRRRGBBGBRRGBBRGGRBGBGRGGBRBGBGRBGRGGRBGGRBGRGRBBBRRBBGGGBGRGBGBGBRRRRBBGRRBBGGGBGGGRBRRGGRGGBRRRGGGGRRRRGBBGRBRBRBGGBGBBBGRRGRRBBGGRBGGRRBGGGBGBBBRRGGBGBRGBBBBGGBGRRGGBRRGBGBGRBRRGGRRGGBGGBGBGGBBGRGGGGGGRGRGGRBRBGGGRGBGGGRBBBBBRRGBRBRRGGBRBBRBGBRGGRRBRGBBGBBBRGBRGBGBGRBGRGRGRGRGGRGGBGBGGGGBRRBBGGGBBBRRRRBGBRRGBBRBRRRRRGBRRGRGRRRRRBRGRRBRGRBRBRRRGRRBBRRRBGGRGRRGRGBRBBRGBRBBGBRRRBBRRBGRRRRBGGGGGGBRRRBRGGRBGBBGBGGBGRRBGRBRRGBGBGBGGGBRRRBGRBRBRBGRGGBBRBRGRBBGGBBGGGGGBGRBGGGRRGRGRBGRGBBRBBGGGGBBBRGRBGBGBBGGRGRRGRBRBGGBGBRRGRRBGGBGGBBRGGBGRRRGRBRRRGBBBGRRGGBRBBBRBBBRBGRBBRBBBBRRGGRRBGBRBBBBBGRGGRGRGGRGBRGGRBBGRRRRBBGGGRRRGGBRGBRGGGBGGGBGGBGBRGBBGGGBGBGGGGBRRRGBBGGGBRGBGBGGGGBBBRBGRGBBRBRGRBGBRBGRGBBBBGGGRGRRBGGRRBRGGRRGBBGRBGBGGBGGGBBGGGGGRGGRRBBBRRGGBRBBGBRRBGBGBGRGRBBGRGBGGBGRBRGGRRGBRBRRGBGGGBBBBBRRGRRRBGRGBBGBRRBGBBGGBGBGRGGRGBGRRGRBRGBBGRBGGRRRRBRRRBGGBRGRBRRBBGRBRBBGRRGGRGBGRBGGBRRBRGBRBGRBRRBBRBRRBGGRRGRGGBRRRRBGBRBBBGBBGGGBGRRBBBBGGBBBBRGRRGBBBRBGGGBRRGRBGGGBGGRRGRRGGBBGGRGRRGRBRBRGRGGRRBRBGGRGBRBRRRBBRRRRRRRGRGRBRBRRGRRGGRBGGBGBBRBBRBRGGGRBRGGRRGBGBBRGRRBBRRBRRGRBGGGRRGGGBBGBBRBBGRGBGGGGRGGGRBRBBRRRGGGBGBBGGBGBRRBGBRRBBBGRRBBBBRBBBRGBRGRBGBBBBGRRBGBBRRBRGBRRBBBRRGBBGBGBRBGRRBRGGRRGGRRBRRRBGRRGRBRGRRGRBRRRRGBGBRRRGGRGBGGGGBRBGGRGBBBBRRBRBRBGRRGGGGBGBRRBRGGBBRGBRBGGBGBBGBRBRBRBGRBGBBGBRRBRGBBGGGRGGRRRRGRGRGRGBBGBRBGRRBBGGBGRGBGRBBRRRRGRRRRRRBBRGGBRRGBBRRBBRRBRBRBRGGGGBBGRGRGRRGRRBRRGGRGBGGGGBGRGBGRRRBGBGBBGGGBGBRRGGRGRGRBGGBBGGRGBGBGBRBGBRRGBBRRGRBGBBGGGGGGBBRRGGGGGRBGGRRGRRBGGBRRRBBGRGRRGGRBBRRGGBRRRRGGBGBRGRBGRGRGBGGRRRRBGRGBRGRBGBRGGRBRGBGGRRBGBBGBBBBGRRRGBGGGGGRBBRRGBBBBRBRRGRBGRBBRBRBBGRGRBGGBGBRGBBRGBBGRBGBBRGRGBRGGGBRGGBRRGRGGRRBRBGGGRGGRRGBRBBRGGRBGBRGGRRBGRRGRGGBGBRBRBRGBBGGRBGGBGGRBBRRRRRRGGBRGRRGRGRBRGGGRBGBRBRBBGGBBGBBRBBGRRRRGGGBRBGGRBGRBRGGBBRGRRRGRGRRBRGBBBGRRBBRBGRGGBBRGRRBRGRGRRGRBRBGRGBRBBGGGRGRBGBGBBGRRBRGBGBBBBGGRGBRGGBRBGGGBRRBBBGGBGRGRBBGBGBBBBRGRRGRBRBGGRBBBGRGBGGRRRGBGGBGGRRBGBRRRRRBRRGGGBRRRGRGBRGGGRGRBGRGRGBGGRGBRBRGGGBGRRBGRRBRGRRGBGRGRRRGRGBGRBBBRGRBBRRRGRRRBGBGGRBGRRGGGRBGRBGBGGGRBGGGBGBGGBGRBGGRBRBRRGRGGGRBGBRRGBBRGBRBGGBGBBGGBRRGBRBRBRRRBRBRBBGGBGGRBBBRGGBGBBBBRGBRBRGGGGBBRGRBBBRRGBRRGBBRRGBRGBGRRRRBGBGRGBRBBGBGGRBGBBGRGBGRGBRBRGBRGRGRRGBBRBGRRGGRRBGBGBBGRGGGBRGGGBBGBBRBRBBRGRGBGRRRRRGRGRBGRGRGBRBGRGRGGGGRBGRRGRBGGGRRBBBBGRBRRBGGRRBBGBBRRGBBGGRRBGGGGGBRGBRRGRGRRBBBBRBBBBGRRBBGGGRBBBRBGGBGBGGBGGGRBGRGBGRRBBGGGBGRBBRGGRRRBGRGBBBRGBGRBBGBBBRRBGBBGBGBRGRRRRBRBGRGBRBBBRGBGBBRGGRRBGRBRGRRBBGRBGGBGRGBBRGRRGGGRBBRRRBBBRBGBRBBRRGBBRGBRRBRBRRRRBRBRRGBRRBRBGRRRGRRBBBRRBGBRGBGGBRBBBBRRBGBBGRBBGRBGBRGGBGGGGRBBRBBBBRRBGRGRGGBRGRGGRRRRGBGGRGRGGBGGBBRGRBGBRBRRBGGRGRRGRBRRRRGGRGBGRRBGRGGGGGBRRBGRBBBBGBBGBBRRRRGGGGGGRBGGGRBBBRBGBGRRRGBRRBGGGBBBGRBGGRRBRBGGRBBRRGRBBGBBGGRBGRBBBBBRBBRRBBGRGGGRBBBGRBGBGBGRBGRBRBRRRGGBGBBRGGRGGRRGRBRBGRBBGRBBGRRGGGRRBRGGBGGGRBBRBGRRGBRBRRBGGRBBBRRGGBGGRBBGGBGGRGBGGRBBRGRGBGBBGRGRBBBRBBBBBGRBRRGBBRBBBGBBBBBRBGBGBGBGGGGRRRRGRBGBRGRRBRRBBRRBGBGRBRRRBGGRGGGRGBRGGGBGGRRGRBRBBGRGBRBBRRBGRRBBRRGBGGGGBBBRBGRGBRGBGRGGBRRRGGBRBRBGBRBBRRRRGRBRRRRBGBGGRBGBRRBRBBGBGGBBGBRBRBRBRGGBGRGBRBGGGBGGGBRRGGRBGRBBRGGGBRRRRBBRBBGGGRBRRBGGGBBRBGBBRGGRGGGRBBRGGRBRRBGGGRRRBBGGGRGBBRRRRGGBRRGBGRRGRBGBBGBRGGBRGBRGBRRBRGGRGBGBRGBRRRRGBRGGBGBGRGGRBGRBRBGBBBBGRBGBRBGRGRBGGBBBRGRBBRRRRGRRGRGGGRGGRBRBBBRGGRGBBGBBGRBBGRRBBGGRGGGBRGGRBBBRRRRBGRGBGBBBRBBBGGBGBBRGGRGRBRGRRBBBRBBGGBGGBGBGBGBRRRGBRRBGGGGGGBGGGRBRBGBBBGRRGRRGRBGGBBRRRBBRGRGRGBGGRBGGRBGGBBGBGRGGBBBGBGGGBBBRBGBRRGBBGRRRBBGGRRBBRGRRRBGRBGGGRGBRRGBBBGRBRBRGGBBGGBGBBRBBBGGBRBRGGGRBBBGRBBBRBGBGGGGGBGGBRGGRRBGBRRGBRRGBRRGBBRGGBRGBBBGBRRBGBGBRGRRBGGRGBGGGGBGGRBRBGBGRBGGBRRBBBRBRBBBGGGGBGBBBGRBRRGRBRRGRGGGGBGBBGBGBGBBBBGBRBBBBGBBGRGRRRGGRBGBRGBRBGBBGGGBGRGGBBRGRBGRRRBGBGBRRGRBBRGGBGGRBRGBBRGRBRGRRGBBRBRRRGRRGRBGGGGGGGRBGBRGBGBBRGBGGBBGGBGRBGGGRRRRBGBGGBRRGBGGGRRBGBGBBRBBBGBRRRRBBBGRBBBBGGRRGBRRGGRGGRBGBGBBBBBGRGRRRRBGGGBRRBGBRBGRBRGBBGBGBBBRRBGBBGRGRGBGRGRBRBRRBBRBGBRGBRGGRBRGGGBBBGRGRBGRBGGBGBBRGRGBGBRGBRBGBRGBBGGRGBRGGBGRGRGGGBRBBRBBGGGRBBRBBBBRBBBGRRBGBRBRRBGBRRBBBGGBGGGRBRBGRGRGRBRBRRRRRGGGBGGRBRBGBGBGBGRRRRBRRBRRBGRRGBRRGBRRBRBGGBRRGRGGGRBGRBGRGBGBRGRGRGBRGBGGBGGRBRRRGBBGRRBGGGGGRGBGRBGRBBGBBRRGGGRRRBRRGRBRGGGGGGRGGGGGGRRRGGRRBRGGRGBGGRGRGRBBBBBGRGBBBRRGBRBGGRRBBRRGRRBGRGBGGGRBRRGRRRGBRGBBBBGBRBRRRBBGBBRRGRBGRBBGBGBRRGRRGBBBBBBBRBGBBBRRBRRRRRRBGBGBGGBRGBBRRRRRRRRRBGGRGGGBGGBGGRGBBGRGGRGGGBBBRBRRRBGRBBBRBBBRRGGRRGGGBRRGRBGGRBGGGBGRBGBBGGRBRGBRRGBBGRGGBBBRGGBGGRGBRGGGRBGGGRBGBBBRBGBGGRRRBBGGRGGRBBBRBRBRGBRRGRGRGGBRBBBGGGRRBGGRGGGGBRBGRRBGRGBRRBGBBRGBBBBBRRRBBBRBRRGGRRRBBRRBBGBBRBGRGRRGBGGGRBGGRBBGGRGRGGGGRGRRRBRBRGGBBRGRRBGGRBRGRGBGRGRRGRGGRBGGRRRRGBGBRGRRGRBGBBRBGRGBGBGBBRGGGBBRBGRRRRRGBRBBBRBRGGRBGRBRGGGRGGGGRGGRRBGRBGBGGBBBRRBGRRBRGGRRRBGRGRRBBBBGRGRGGRGBRBGBBGBGRRRGBBGGRRRBBRBRRBBBRGGGRRRRGRBBGBRBRBGRBRRBRBBRBBBBRBGGBBBBGBBRBRBBBBRBBBBRGBBBGBGBGRGBRBGBBRBGRRBRBRBBBBRBGBGRBRRGGBRGGGGRBRRRGBGRRGRRGGRBRGRRGRBBRRGBRBRBGRRBRGGRBGGGRGGBBGBBRBBGGGRGGGGBGGRGRGRGRBBGGGRGRRGGGGRBBRRGBGBGGBGBGBRBGGGBBBBRRRGGGBGGRBGRGRBBRRRGRGGBBRBBBGBRRBBGGRGBBBRGBGGRBBBRGRBRRGRGRGGRRGBBGRRBRGGRBRRBRBBGRBBGRRBGGGBBBRBGGBRBBGBBBGGRRGGGGRRBGRGBGGGGBBGRBGBGGRGGGRBBRRBGGRGGRRRRBRBGBRGGRBGBRRGBRRGGGRRRGGGBBBBGRBRRRBGRBRRBRGGGGRRBBRBRRGBRGBBBBBBRBGRBBRGBGBGRGBBRRBRGGGBRRBBRBBRBGGBGGGRRGRGBRGBGBGRRBRBRBBGGBGGGRGBBBRGGRRGGBGRGBGBGGGBRGGBGBGRRBBGBRRGBRBRBGGRGBGRRBRGGGGRGBRRBRGBGGRRGGRBRBRGBGGRBBGRGBBRBBGGGBGBGBBRGRBGRGBRBBRGGBRGRBGBBRBRBRRGRBBGGBBGGRGGBBGGBGBRGGBGGGRGRRBRGBRBBRRRRRBBBRGBGRBRRRBGGRRBRRRGRGGBGBRBRRGRRRRRBRGBRGRRGGBRBRGBGRRGRGRRBGGRRGGBRBGGBBBRGRRGGRGGGBBBGBRRGGGGGRRGGBRRBRRGRBRGBBRRBBBGGRBRGBBBBGRRRGRRBBBRGRBGRRBRBBBGBGBRRGRRRGGGRRBBBBBGBBRRBBGBGRRRRRGRRGGRGRBGGBBRGGBGGBRGBBGRRBGRRRGRRRGGGGBBRGRBGRGBRGGBGRBBBGRBGGRGBBRRGRRGBGGGGBBGBGGGGRRRBRRBBGRBRGRBBBRBRGBRBGBGBGBRBRRRGGBRRRRGBBGBGBBBBBRGRRBRBBRBBGBGGGBBRGGBRRBBRBGBGRRGGRBRRBBRGRGRBGRBBBBBBGBBGBBBBRGRGRGGRGGBGRRGBRRGBRBRBBBRGRBRRRGBRBGRGRGBGGGGBRRBRRRRBBGGRGBGBBGGGBBRRRGBBBRBRGBGBBBRBRBRBGGRRRBRBGRRRBRBRGGRGRBRBGRBRBBRBGGRGRGGBRBBBBGBBGGRGRGBRRBRBBGBGRGBRRGRRGRGGRGRGBGRRRRRRBGRGRGBRRBBRGBBRRRGRBRBBGBRBRGRRRGRRRBBRRGRBGBBBRRRRGRRRRGRGRGBRBBGBRGRRRRBRGGBBBGBGGRBBBBGBRGRRRBRRGRGBBRBRBBRBRGGBGRGGBRRGGBGBBBGRRBRBGBRRBGRRBGBGGBBBBGRGRBGBBBBRBRBGRGGRBBGBGGRGRRRRBGBBRGBRRBGRRGGGBGBGGGRBRBRGBGBGBGGGRRGGRRBGGBRGRBRGGBGBGBRGGBRGBGBBBGGRGGGBGGGGBRRRBGRGGRBRGRBRBGRGRRBGGGGRRGGBGBRGRGBRBBGRBRGGBGRBGBGRGBRBGBBBGGGRBRRBRGBBBRRGRGRGGGRBGRBRGRRBBRRGRRGBBGGGBRBBGRGRGGGGRGBBGRGRRBRGRBRGGBBRBRRBRRRBBGRBRRGBRGGGGBRBBGRRRRBGGBGGRGRRGGRBGRGBBRGRBGRBBGRBBBGRBBGRBRRRBRBBGGGRRRRRGBRRRRRBBRRGBGBBBBBBGBGBBRRBRGBBRRBGRRGRRGRGGBRGRRRGRBGBBBBRGBBBRBBGRRBRRBGGBBBRRGGRRRRGRRGBBBBRGGBGBGRBBBGBGGBBRGRGGGRGGBGBGGRRBRBBBBGGRRRGRBBRGRBRBBBGBGRRRGGBGBRGBGRBRGBRGGRRGRGRRRGBBRGBGRRGBRRBBRBRBGRGBBBGBRGBRGRGBBGGBGBBBRBRBGRGGBRRGBBGBGGGRGRBRGGGGGGRBGGGBBRRGGBRRBGGGBBBBBBRGGBBRRGRGBBBBBRRRBGGBBBGRBGRBGGGRGGRGBRGBBRBBRRRRBBRGGGBGRRGBBBBRGRBRGRRGRBRBBRRBBRGGRGRRBGRBBBBRBBBRGRGGRBRBRGRRBGBBRRRRBGBGGBRGBBBRBBBBBGBRBBRBGGGRGBRRGRRBBRGBRGBBGRBGBGGGBRGGGRGBRBRGBGGBGBBGGBGRBRGGRGGBGRRRRRBGBRRBBBGGRRGBRBRRGBRBRGBBGRBBRBGBGBGGGRBGGGGGBBRRBRRGGBRRBGBRGGRBGBRRRRBGBGGGGGBRGBGRGBGGGRBBBBBGBBBBRBBGRRBGBBGRGGGRRBBBRBGGGGRBGBGBGRRBGGRRRRGBGBBBBBGGBRRBBRGGRBGBGRBBGBRGRGRBBGGBGRRGGRRRGGGBGBGBBRBGGRBBGGBGRRGBGGGRRGRBRBGRBRBRBBGRRBRRRBGGGBRBBRRRBGBRRGGBGGBGGBGBGBBBBGRRGGRGGRGBGRRBBGBGBBBGGBGBBRGBGBRGBRBGBGRRBRRBGRGBRGRBGGBRRBGBBGRGBRGGBBRGRGRBBGBBRRGGBBRBGBRGRRRRGBRRGRRBBRBGRBRGBRRRRGRGRRBGGRBRRBGBRBGBBGRRGGGGBRGBGBGBRBGGRRBGRGRRRBRRBGGGGRRRRRRRRGRRRGRGBRRRBGBBRBRRGBBBGGRGGRGGRBBRGBBGRBGBRRBBGRRRRGRGBRRRGBBGBBBGBRBBRRRBBBBRBRRGGRBRGRGBGGGGGBBGRGRRBGRBGBRGGGBBGBGRBBRGBRBRBGGRRBRGGBRBBGRRBGRBRBRRGGBGGBGGGBGBRRRGBBGGGBRRRRRGBGBGRBRGGBGRRBRRRGBBRRBGBBRRRGGRRGBGRBBRRGRRGGRBGBRBRBBBBBBRGBRBRBRBRGBRBRRGRGGGGGGGGRGRRBRBGGGBRBGRRGGRRBBRGRBBBRGRGGGBRBGBRGGRGGBBBRBBGGRBBRRGBBBGRRRGBBRBGBGBGRGRGRGBRBBRRBBRBBGRRGGBGBRRBGBRBGGGRRGRRGGGGGGRGBGGGRGGRGGRRGGBRBBRRRGRBRBRGRGBRRRBGRRGGBBRGRRGBBRRBGGBGRBGRBRGBBGRBGBGGGGRGBRGGRBBGRGGGBBBGBBGBRGGBRRBBGBRGBGRBGBGBGRGRBRGBBBBRGGRBBBGBBBRBBRGRRRRBRGBRBBRBBRRGGGGGGGRRRGBRBBGRRGBGRBBRBBRGRRRBBBGRRBGGRRBRRGGGRRRGRBGBRRBRRBBRBGGBRBBBGGBGRRRRGRBBRGBGGBGRGBGGRBGBRGGGBRRRBBGGBGRRBRGBBGBBRGRGRBGGGBRGGGBRGGBRBBBBGGBRBBBRRRRBGGRBBGGRRGGGBRBBRGRGRBRRBRGRBGBRRGRBBGBRRGGRBRRRRGBRRRGRGRBRGBGBRGBRBBRRGBGGRBBGRBBGRRRBGBRRGGRRBRRBRBRGGBRBBRRRRBBGRBGBBGBBBRRBGRGGBBRBBGGGGBGBGGGBGBGBRGGRBGBRBBBRBBBBGGGGRRRRBBRGBBRRGBGGGBBBBGRGRBRRGBGBRGRRGRBGRGBBGRRRRBRBRRGBRBBGBRGBBGRBRGRGBBGRRGGGBGRBBBBBBBBGRRBRRRRGGRBRRRGGRRBBBGBBRRBRBGBRBBGBBGGGBGBRBGGBBBGBRBGGBGBBRGRRGGRRRBBRGBRRGBRRGBRBBBRGRBGGGBBBGBGBBRRRRGGBRBRBBGGBRBGGBRRGRRGBRBGRGBGGGRRBBBRBRGGGGGRBGBGGBBGBRGGGRBBBRGRRRRBGBBBBRRGBBBBBBRBBGRRBRRBRBBRRRGGGRGRGBBRBGBBGRGGGRBGGRBBBBRBRGGBBRBRRGGBRGGGGRRGGRRRRRRRRGRGGRRRRBBRGGRGBGRBRGGBGBRGRGGGRRRBRRBRRBGGGGRBGRBBGGBBRRGGGRBBGBGGRBRRGBBGGRRRBBBRRRGGRRRBGRBRGGGGRBRRGRGRGGRRGGGBGBRBRRGBBGBRRGGRBGRRBBRGRGBBRGGGGBRBRGGBGGBGGGGRRRRRBBBGGGGGRRBBRRBRBBGRRRBBBBRGBBGBGBGRGRGGGGGGBGGGRBRGGBBGGBBGBBGRGRGBRBBBGGRGRRRRRRRGRRRBBRRBBBRRRBGGBGGBBBRRBGGGBGBRBRBBBRBGRRRRRGBGBRGBGBBRGGGRRBGRRGRBBRBRGBGRGRGGBRRRBGGGBGBRRGGGRBGRBRRBRGBGBGRGGRBRGGRGBBRRGGGBGRBGGBRGGRRGGRRBBGGGBGGBGGBRBGRGBBRGRGGBBBGGRBBRGRGRBBBGGBGGRBRRBGBRRGBRRGGGGRBBGGRGGRBGBBRRGRGGBGBRRBRRGGBRRGRGRGRRGRGGRGGRBRBGGBGGBBRGGRGBBBRGGGBBRRRRBBRBRRGBBRBBRBRBRBGBGBRBBBBBRRBRBGRRBBGGRRGRRGRGRBRBRBGBBGBGGGBGRRRBBGGGBBBRRRGRRBBRGGRBBBGGBRGRGGRGRGBBGBBBRGGRRRBRRBBRRGBRGRRRBRBBRBGBGGBBBRRRBRRBRRBRGBGRRBGRRRBGGGRRRRRRRGGRGGBGRRRGRGBBGGBBBBGRGBGBRBBGRRBBRGRRBGGRGBRBRBBBGBGGGBRBGRRBBBGBBBRBBBRRGRRGRGBBRRRBRGGGBGGGBBRBBGGGRBGBRRGRBRGBGGBGRRRRBGGBGBGGRGBRGBRGRBRBRGBBRGRRGBGGRBGRBRGBGGGRGBBGGRRRGBRGRGRBRGBBBGBGGGBGBGGGRGBRGGRRRRBBGRBRGGBRBGRBBBRBRBRGBGGGBBBRBBRBBRBRGBBBRRGRRGRGGBBRRGBRRGGGRBGRBGGGRGRGGGBGRBBBGRBBGBBBGGGBGBBRRGGGBBBGGGRBBGGRGGGRBRBRBBGRBRGGGGBBGRGBBGGGBRRGRGGRBBGRGBGRRRGBGBGBBBBGBBGBRGGGBBGGBRGRRRBGGGGRGRRRGBRRGGBBBGGBGRRGGRRGGBRRGBRRBRGRRGGBBGBBBRGGGBGBRGBBGRBBBRRBRBGGGBGGGRRBBBGRBBGRRGBBGBRGBRRRRBGBBRGGGBGGBRBGRGBBBBGGGGBGRRGGRGRRBBBGBGRGBRGRGRBGGBBBGBGBBRGBBBRGBRRBBRGGGBBBGBGBBRBGBGGBBRRBBRBBGBGGRRBGRRGGRBGBRGGRRBRBBRRRBBBGBGRRBRBBRRBRRRRGBBGRGGRBRRRBBBRGGGGGBRGBGRRBGRRBRGBBGRBGGRGGRBGBGRGRBBRGRRGBBGBBGGBBBBGRRRRGBBGRBBGGRBRRRGRRRBGGGGGGBRBBRBRRGGGBGGRGRGBGRRRBRGGBRRRBGBBBRBRBBGGGRRRGBBRGRGRGBGRBBGRGGBRGBGBBBGRGBRBBGBGGRGBRRRGRGGGRGBBGRGGRRBGBGGBBGRRRBRGRRBRRGBRRBBRRGBGBGGBBBRGGRRGRGGGBRBBRBBRGBGBGRRGBGRBGRBGBBRRRGGBBRBRBBGGBRRRRGBRRGRBBBRGBGBBBRBBGBBGBGBGGRRBRBRRRRRRRGBBRBGBRGBBGBRRRGGBBGBBGBRBRBBRRRBRBGRBBRGRRRGGBRGBBGRGGGGGRGBRGBGGGBGRBRBBGRBGGRGGBBRRRGBGGBGRGGBBGGRRBRGGGRRRGBBGGRBBBGGRGRBRGGRBRRGBGRGRGBRBBRGGGRGRBBBRBGRBRRGRGRRRRRGGRBGBRBGBBBBGBGBRRRBRGGGRBRGBRRBRRRRGRBRRBBBRBBRBRRGGGBBRRBGRBRGBRRRGRRBBRBRBGGBBGRBRRGGGRRBRRGBBGRRGGRGBRRGRGGBRGGGRGRGBGRRBBRGGBRRRGBBBRGBGBBBBBGBGBGRGBGRRRRGBGBBBBBBBGBGGRGGBBGRBBGRRGBRGBBGGGRGGRBGBGRBBGRBGBBGBBGBRGBBGBRBGGGGRGBRRBBRRRBBBRGGBBBRBBRRBGRGRBRGRBBRBBGRBGRBGGBGBBBGGRBGGBRBBRGRBGBBRRGRGBRRGRBGBBRGBBBGRRBRRRGRGRGGRBBRGGGRGBBBGRRBGRGGRRGGGRBBRRBBBBRBRBRBGRBGGBGBRRGGGRBRGBGBRRBRBRRRBGRGBBRRBGRBBGRGBRBGBRGRRGGRGGGRBBBBGRRGBGGBRBRGBRBRRGRGRBBGGGBGGRBRRBBRGRBGRRBRGBGGGRGGBGRGBGGRGRGBRGBBBBGRRGBBGRRGGBRBRBGGRBGBRRGGBGGBGRBGBGRGRBBBBGGRRRGGRRRBGBGGRRRRRGGBBRRRRGRBBGRRBBGRRBRBGGRRGGRGBBGBBRGRBGRGRGGGGRGGBGGRBGRBRRGRRGGRGBGRGBBBGGRBBBGGGBBBBGGRGBBBRRGBRRRBRRBGGRGRBBBBRBGBGBRRBBRGRBGGBBRRBRGBGBRGRGRRGGRBGGBBGRRBBGGBGBBBRGGGGBGBRGBGGRGRRGBGGRGBRBBGRBRRGBRBBGRRRBRBGGRGBRRBGBGGRRBRRGGGGGBGRBBBBBGGGBRGRGGGGBRGRBGGGRRRBRGRRGBGRBBRGGBBBRRGRRBRGGBRBGRBBBRRRRGBRGRBBBBRBBGBGBRRRRRBBGBGGRGBGRBGBBRBGBRRRBRBGGBBGBRGGBBRBBRGBRBBRGRBGRGGRGGBBRBGGBBBBRRRBGGBGBRBRRBBGGBBBRBBGGGRGGBGBRBGBRGGRGGGBGGGBRGBRRBBRRBGBRRGGBRGGBRGRGRRGGBRGRRBRBBGGBRRRGBBGRRBBRGRBGGGBRRGGRGBGGGRGBRBRRGBGBGGRRBRBRBBGBGRRRRGBGBGRRGGGRGRBRBBRGRGRBGBBBRRRRBRBBBRRRGBRBGRRRRGBGBRGRGGGGGBBGBBRBBGBGGGGRGBRRRRGGBBBRRRBBBBGRGBBGBBBGGGGGRBGGRBRBBBRGRBRRGBRRRRGBGBRBRBRBGGRGGGBGRBBGRRRBGRGGBRGRBBBGGGRBRGGBBGGRGGBBGBGRRBGBRBRRBGGRBGRBBRBBGRRRBRBBBBBRBBGBBGGBBBBBBRBBGBBBGRRRRRBRBBRRBGRGGGRGBRGGGGGBRRBGGRBGGBGGBRGGBBRGRRRBGGGRBRRBGRGGRGBBRBGRRRBBBBGGGBGRRGGRBBBGBGBGRBGBBRBBGBBGBGRGRRGGGBGRBBGBGGGBGRGGGGRRRRBRBRGRRRBGBGGBRGRBRBBBRRRBBGBBGBRGRGRRGRBBBGBRRRRRRRRRGRRRBRRBRRGRRGGBBGBBRRRGRGBRGRBBRBBRRRBGGRBBRGBBBBBRBBGBRRGGGGGBGGRBBRGGGGRBRBBRBBRGBBBRGRRBBGBRRRRRRGGRGBBGGBGBBRRBBRBGGBBRBGGRRGRRGGGBRGGBRRGRRRBGRBBBBGRGGGGGGGBBRGBRRRGRRRBBRGRBRRBRRBBBBGRRBRBGBBBBBRGRBRBRGRBRGBRGBBRGGGGBBGRBRBGRGBGRBGRGGGGRRBBBBRGGGRGGGGGBRBRBBBBBGGGBBRGBRRRRGGBRBRBGGRBBRBRRGBRBGBRRBBRGBGGGBGBBGBGRRGRGRGGRBGBRGRGBBBRRRBGRRGRBGBBGRRBGBGGGBBGBBRGRRGRRRBBRGBRBBRGRRRGRBRBGRBGBBBRGGRGGRGBBGRGRRBGGRRBBGBGGGRGGRBBBRBGGRBRRBBGRGRBBGGGBGGGBGRBBRBGGGGBRGGRRRGGRBRBRRBRGRGBBRGGRRGGRRBRGGGBGRGGRBBGBGBBBGGGGRRBRGGGBGBRBRGGBBRRBBGRGRBRRGBGGRGBBRBBBGRBBGGBGBBGRRGGBGRBRBRBBRBBRGBRRBBRGRBBGGGGBRBGGBRBRBGBBGBRBGRBGRBRGGRBRBRRBGGBGRGGBRBGGGBRGBGBRRRRRRRGBBGBRGGBGRBGRGRGRBRGBGGGBGGRBGBBRGBGRGGGBRRBBRBBRRBRBRGGBRRBGRBRGBGBGRGRGBGRRGGGGRBRRRBRGBRBBRRBRBBGRRBBRGRBBGGRBRGGGRGBRRGBRRGRRGGRBGRRRGRBRGRGGGBBBGGRGGBGGBBBRBBRGGBBRBBGGGBRRBRBGBBBRRBBRBGGBBRGRBGRBGGGBBBRGBRRGGGRBRRRRRGRRBBRBRGBBRRBBBRBBRBBBRRGGGGBGGRGRBBRRGRBBGBBGRGGGGGGBGGGRBGBGGGRGGGBRGBRBBBGBGGGRBGBGBRBBGGGRRBBBRGRGBRGBBGBGBGGGRGRBBBGBBRRBBRBBBBGGRGRRBRBBBGRBRBGRBBBGGRBRGGRRBBBBRRRRRRBRBGBRRRRRGRBRGGRBRGRRGRRBGGRBBBRBRBBGGRBRRGRBRGBGRBBBRRGBBGGBGBBBRBGBBRRRBRBRBBGBGRGBGGGGBGGGGRGGBBRBRRRRGRRGBGGGRGGBBRRBBBGRRRBRRRGRBGRRBGBBBGGRRRRRGGBRGGGBGGBGRGBBRRBRGRBBBGRBBRBRRBGGGRRBBRBRBBBRRBGBBRGGBBRBRRBRGGBBBRBBGBBGBBBBGRBGGGBGGGGBBGGRRRRRBRRGBBBBGGBGBBBRGGBBRGGRRRGRGBGRRGGRBGRGRBBBGBBBBBBBGBRGBBGGBRBBRRBRBRGRRBBBBRRGRRGGBBBRGGGGBGRBBGBRGGRBGRRGGGRBGGRBGRBRGGBRBRRRGRRGRRRBGGGRBBBBGBGRRGBBBGRRBBRGBGRRBRRGRBBBGBGGBRGRGRBBBRBRBBGBRGRRBGGRGBGRGRGRGGGRBGBRBGRGGBGBGBRGRBBGGRBBRGGBRBRGGBGRBGBRGGRBRRRRBRRGRRGBBBGRRGGBBBRGGBGRRBBGBRBRGRBBRRGBGRRBBGGGGGRRGRRRBRGRGGRBBBGBRGRGGRRGBGGGRGBRGRRBGBBBBRBGBGGBBBBGBBRBBGGRRGRRGGBRBBBGBBBBBGBGGGGGBGRGRBBGRRGRBGRGGGRGRGRBBRBGBRRGBGRBGRGGGRBRBRRGGRBBGGBBBBGBBGGBBBBGBRGGGRRGRRRGGRGRGGRGGGGRRRRRBBBRBRGGRBRBBRGBRRRRBRBRBRRRRGRGRBGRRRBBRBGRRRBGGBBRRBGBBBBGGGBGGRBBGBBGBGRBGBBBRGGGRRBGBGBGRGGBBRBRGBRRRRRGRBBGGGRRGBGRGGRBBGBBBBBRGRGGRGRBGRRRGRRBBBGGRGGBBRBGRBBGRGRGRRRGBGBRBRGBBBRGGBRGRGRRGRGGGGBGRRRBBRRBGBGGGRBRBGGRBRRRRRGBBBGBRBBBRGBBRGRRGRRGGRGGGRGGRRGBRRRGRRGGGGRBBRRGGGBRGBGBBRBRBRBBGRRBGRRBGRBGBBBRGBGRGRGRGRRGGGRGBBRRBGGRBGBGGGBRRGGRGBGRRRGRGRGGBGBBRGRRBBGGGGGBBRBBRGBBGBBRRGGRRGBGBBGBGRRRBRBGGBRGGGGBRGRGBGGGGRBRRGRBGGBGGGRBRGGGBGGRBGGRGBBBBGBRRRBBBGGGRGGGRRGRGBGBBRRRBBRRGRRGGRRRBGGBRRGBGRBBRRBBGBRBGGBBBRGRGRBGBRGRGRBRRBRGRRGBBBGBRGBRBBGBBRGGGBBRGBRGGGRRBBRBBGBRRBGRGBRRRGBBBBRRGGGRRRGBBGBGRGGGGBGRBRGRGGRGRGGGBGBRGRBRBBBBGRRRGRGGRBBBGRGGGRGRGGGRBGRBGRBRGRGRRRGGRGGBGRGRRBGRGBRGGBRRBRRGGBGBBGGRRRRRRGRGBBGRRBBGGRBRGGRBRGGGRRBGRBGGGBGRBBGBBRGGGBRBRRBGBGRRBBGRBRRGRGGBGRBBRBRBGRBBGGGGGRGRBRGRGGGGRRBBRBGBGBBRGBRBGRRRRBRRBRRRGBRBRBBGGRGGRGBGGRGRGGGGBBBGBGRBRGGGRGGBBBGBGGGBBBGGGBRRGBRBRGGBBRGRGBRRRBRGGGBGGRBRRBGBGBGRRBRRRGRBBBBBGGGRBRGGGRBGRGGBGRBBGRGGRBGBGGBRBRRRBGGGBGRBBBBGRBGGRBGGBBRGGBGGRBBBGGGBBBBBBBGBBRBRRRGBRBRGGRRBRBBGRGGRGGRRRGRRBRRBRBGRGRRRRRRGGRBBBBRRRRRRBGGBBBGRRRBBGBRBRGRBBGBGRBGRRBGRGBBRRGBRBGBGRRRRBBRGRRRGRBGGBBBGRGBGRGBBBGGRRRGRBBBRRRGRRBGBBRGRBGBRRGBGGBGBBRBGRBGRRRRGBBGBRRGBBRBRRRGGBRRBRBGGBRBRRRGRRBRGRGGBRBRRRGBRBRBRRRBRRGRGBBGRBGBBRRRGBGBRBGRRBBRBRRRGGGBGGRBGBGGRGBGBRRBGBGGGRGGBGBRRGRGRRGBRBRRBRBBGRBBRRRBBBGGGGBBBBGRGRBBRGGBBGGRBBRRBGRBGBRBRGGGRGGBGBBGGGBGBGGGRBRGBGRRRBBGRBBGGBBBBBGRRGGBRRBGGBBRRGRGRRBGRRBGBGGGGGBGBGBBGGGBGGRBBRRRBRGRRBRRGGGRBGGBBRBBBGBRRRRRGRGGBBBBBBRGGBGGBBGGGGGRRGBGGBGRGRBRGGRRGGGRBBGGRRBGBBBBRGRBBBBGRGBGRBGBBRRGBBBBRBGRGGRBRGGRRGGGRGBBBBGGBBBBBGRRGGGRRGBBBBBBGBGGGGGRRRGRRGRRRGRBRGRGRRGBBGRRRBRBRGRBBBBRRRRGGBGBGGGBGRGBGGRRGRBRRRBBBBBGRGRBRGBBRGGGGRGRBBRGRRGRRGRGRRBGBRBRGGRGGGRRGRRBBGRBBBGRRGBGBBRBBRRRBRBRBRGGRBRBGGRRGBGBGRGRRBRBRGRBGBRGRBGGGBGRBBBRBRGRBRRBRBRRRRBBRRBGBRBBBGRBGBRRGBRGBBGBGGBBBBGRRGBRGGRBGGGBGBGBBBGGGRRRGRBGRBGGRRGBRBBBGGGBBRBGRGRGGGRGRBBGGBBBRRBGRBRGRRGBRGBRBRRBGGRBRRRRRBBBGBRGGBGBBRRBGBGGBBGGRBGGGGGGBGGRRBBBGRBGRBRBBBBBBGRRGBBBBGGBRRBRRGGBRRRGRGGRBGBBBRRGGRRGGRRGGBRBGGBBBBGRGRRGBBGGRGRGGGBRBBRGBRRBBBGBBBBBRBRBBGGRRBBBGBRBRRRRGBBRGGBBGBGBBGGBRRBGRBGRRGBRGRRBBGRBBRGGBBGGGGRBGRGRRBRRGRGBGGBBBRBBRRBRRRBBGBBGRGGGRBGGRBGBBGBBGGRBBRBRRGRRGRGGGRRGRBRGRGGRRGRGBRRBRRRBGRBBRGGGBBRRBGGBRRRRGRBBBBBRRBBGRBGGGRGRRGRBGBBGRBBBGGGRBRRBGGBGRRRRGGRBGBBBBRRRRRRGRBGRGBRBGBGBGGBRRGRGGRGRGBBGRRRGBGGGGGRBBBRGGBGBRBGGRBRBGBRBBRRBRBGGBBBGRRRBBGGGGBRBBGGGRBBRRRGRRRRRRRBRRBBRRRGRRBRRRBRBBBRBBGGRGGRRGBRBGRBRGGGRGGGBGGBRRGGGBBGBGBBRBRBGRBBRGRGRGBGRBRGRGBGBBGBGGBGRBGBGGGGBGRRGRGGBBBGBRBBRGGBRRGGBRGGBRBBBRBRGGGGBBBGRRRGGBRBBRGBGBGRRGBRRRRGBRBGRRRRRRBBRGBRGGGBGBBBGBBGBGRBBGGBGBRBRBGGRBGGRBGBBGBBGBRGRGRBRRGGBBGBBBGRBGBRRGBGRBRGBGBRRGRRGBBGRRRBGRBRGBGBGBRBGGRGRRBRBRBGRGBRBGBRGRRBRRBBBRGRBBBBRBGRBRBBBGRGRRGGGRGBRGBRBGRBRRRGRGBBBBRGGRGBGRGGRGGGRRBRGRBRGBBBGBBRGBRRRGRRGGGRRBBRRBRBRRRBRRBBRBRGBRBGBRGGRRBRRGGRGBRGRGBGBGRBGRGBBGRGBBBBRBRRBBGRGBRRGBGRGGBGBBRGRGRRGRRGGGBRRGGBGGBRGGRGBGBRRBBGGBGBGBGBRRRRBGGGGGGBRBGRRRRGRRBGRBRBGGGBBBRBGBGBGRBGBGGGGBBBRRGRBBRGGBGBBBBGGRRBRRRRGRGGBBGRBBGBBGRGBRGBBRRGGRBBRRBRRGGRGRRRBBRBGGGGGBRGBRGRGRRRRBRBGBRBBGRBGGGRRRBBBBGBGBRBRRBGRRRGRBBRRBRBGBRBRBGRRRRGRRGRGGRBBGGRRRGGGGRRBGBRGGRGRRRRBBBGGBRRGBGBRGRBRBBBGBBBRGBRBBBGGGRRGGBRGGBBBGGRRRBGBRGRGRGGGGRRRGGGRRGGGBRGRBGGBGRBBGBGRGRGRGGRBRBBRBGRGBGBGRRGBRRRGGGBRGRGBRGRRGBBRBBBGGGRBGGBGRBRBGGRRGGRBGGRRRRRRBRBGGBRRGBGBBBBGRRGRBBRRRRGBGBBRBGGRGBRGBBGBRGRGGGBGBRBBGRGRRBGRRRGRRBBRRRBRGRGRBBBGBBGRRGRRRRGGGRGGBRBBBBRRRRGRBGBGRRBRGGBBGGGBGRRGBRBGRRGRRRRRGBGBRBGRRRBBGRGRGBBRRBGGGRBGGBBRBGGRGBRGBRRGGBBBBBRRRGBGRGRBGRRGRGGGGBGGRGBGBBBBRBRRBBBBRBBGRBBRBGGRGBBGBBGBRRGRRBGBGRBBBBGRBGRBBRBGRBRRBBRBBGRRRGRBBGGGRRBRGRBBGBGRBGRGGGGGRGBBRGGBBGBRBBGGRGRBGGBGRRBBGBGRGRBBGGBGRBRRGGBBRBBBGBRGBRBBBRBBGBGGGGRRGRRRBRBRBBBGGRRGRBGGRRRBRBGGGGBBBBRGRRGBGGGBGBGRBBBRRRRRRGRGRBBBRRBRGGGBGRRRBGGRBRGBGGGGRBGRGRGBRGRBBBBGBRBRBRRGGBBRRRBGBRGGGRGBGBGBBRGGRRBRGRBRBGRRBRGBGGGBGRBGRGGBBBGRGBGBBGRRGRRRBBGGRRGBRGGGBRGBGRRBBGBRRBRGRRBBBGGRGRGBGRRBGBGBBGBRRGRRRRRGGRGBGRRBGGGRBBBGBGGGBRBRBRBBRBRRBBBRRBBGBGRBGRRRBGBGBBRGBBGGGBGRBGRRGRRRGRBRRRRBGBBGBBBBGRGBGRRGGRGBRGGBBGBRBRRRBRRBBBBGGRGRRGGBGBBBBRBGBBBBBGRBGRBGGBRBBBRRGGBGRGRRRGBRRBBGRBGBGRGBBBBBGBBRRBGGGBBGGBBBGBRRBGBGBGRBRBGRGGGBRRRGRRGBRRBBRRRRBBGGGBGGGBBRGRRGRGBGBRRBBBBRBBRBBBRRGBRBBBRRRRGGGGRGRRGBRGBRBRBGBRRGBRGGRGGGBRGRRGRRBBRRRRBBGGBRRBBBRRBGGGGGBBGBRBRBGGGRGRBBBBRBBBRRBBBGRRBRBGRRGRRRGBRRBGRGRGGGRGGRGGBBBBRBGRRRBGRGRGBBBRGRBRGRBGGRBGRBGGGRGBGGRBRRGRRRRBBBRRRRBBGBGBBRRGRRGBGGBBRRBRBRRGRBBGBBGGBRGGRGBBBGGGRGGGBGGBBRGRBRBBRRRBGGGRGGRRRGBRGGBGRBRBBGBBBBGRGBRRBBRGGRBGRBRGGBBGGRGGGGRRGBGRRBRBBGRRBBBBBBGRRRBBGRGBRBGGRBBRBBRGGGBGGBRGBBBBRRRBRBBRGGBBGGRGBRRRBRGGBRBRRBRGBRGGBGBBBBGGGBGGRBBRBGGRBGRBRRBRGRBRBGRRGBBGBRBRBBRRBBRGRRBBGGRBBBGBRGRBGBRRGRGRRBGBBGRRBRBGGBGGBBGRBGRRGRBBRRGGRBRBGBGGBRBGGGRRGBGRGGBBBGBGBRBRRRGBRBGBBRGGBBBGGRBBBBRGGBBGRRBRGRGGBBRBBBGBBRGGGGGGGGGBRGGGGRRBGGRRRBBRBRRGGGBGRBBGRRGBBBGRRGGGRBBGGBBRRBBRBBGRGRBBBRBGRRBGBRGRRRBBRBRGBRBGRRBBGGBRBBGRBBGBRBRGGRGGBBRBRBGRBGRBRRBBBBRBGGBBBBGRBBBBBRBBBGRRBGBRBBBBGBBRBGRBBGRBGBBGBBRRGGRGBRBBBGBGBGBBRBGBGGBRGBGBGBRBGRRGGBGRBGBBRBGGBBGBGRRRBRRGRRGGGRGBRRRRBBBBBRRRRRBBRBGGRGRGBBRRRGRRBGGBGRGGBRBBRGRGGGRBBGRBGRGGRGGRRBBGGGRRBBRBRRBRBBRRRGRGBGBBRBRRBRBRBBGGBBBRRGRRGGGBBGGBRBBRGRGGRGBRRRBRRBGGGBBBGRBRBGRBGRGRGRGGGGRBRBRRBGBRGGRBBRGBBBBRBRGGRBRBBRBBRBBRGBRBGGRBGBBRGGGBRBRGRGGBBRGRRGRGRGGRRGBGGGRRRGRRBRRRBGBBBGRRBRGGRRGRRRBGBRBBBBRBRRBRBBBBRRBBGGGBGBBGRBGBRRBRRRBGGBGGGGRGBRGGBGRRRRRBRGGRGGGGBGRGRBBBGRGGGGRRBGGRBBBBRBGBGRGGBBBRBRRGRGBBRRBBGGRGRBRGBBGGRRBRBBRGBGBGGBRGRRGGRGBGGGRBGBRGRRGBBRBBGBGBRBGRBBRRGRBRBRBGRBBRBBRRBBRRRGGRRBGRBGGGRGGBBBRBBGBRRBRRRGGRBBGBGRRGBGBRRGBBGGGRBGGRBBGBRBRBBBBGBRGBGRBRBRBRGBBRRRRBGGBGGBGGBRGBGBBGBBGRBRRRBRGGBBRRGRGBRRGRBRRRBBGBBRBGGGBGBRBGRGBGBBGBBRRBRRGRGRBRGRRRBBBGGRGBGRGRBRRRRGRGBGBRBBGRBGGGGRGRRBRGBBBRBGGRBGBBRGRRRBRGGBRRBGGRGBBGGRBGGRGGGRRBBRBRRRBGBGBRBGGGGGRRGBGRRRGBRBRRRRRBGGRGBRBBGRGBRGBGGGRBGGBGGRBRRGBGBRGGGGRRBBRBGRGGBBRRGRRRRBGGRGRRBBGRGRRGBGGGRRBBRRRBGRBBGBRBRGRBGBRBBBRBRGGRGRRBGGGRBGBRRRRRGGGRRGBRRRBBBRRBBBGRRRGBBGRRGGRGBBGBGBBBRRBRGRBRBRGRGRBRBRRGBBBGGBBRBBRBBRBGRGGRRRGGGBRGBRBBBBGGBRGGRBRBRGGGBRRRGGRRRRGGRGGGGBRGRGBGBRRRGBBBRBRBBRRBRGRBBGRGBRBBBBGBRBBGBRGBBBBGBBBGGRRBRGRBBRBGBRBRBBBBBGBRRGGRGGBRBBRBGRGRGRBBGBBRBBRGGRGBBGBGBGBGGBGRRBGRRBBGGBRRRRRBRBGRGBBGGBRRBBGBBRBRBBBRBBBRGRBBBRBGBBRBGGBRRGGGBGBGGGRGBRGGRGRBGGGBRGGRRGRGRBRRGBGBBBRBBBRBRRRBBGBRGGRBRGRGGGBBGRBRGRBRBRGRGGRGBGGGBBRGGGBRRGRGBBRGBBBBRGRBBRRBGRGBBGRGRRGGBBGGGGGRGGRGBRGBBRGRGRRRRRRGRBRBBBBRRRBGGRGGGBRRRBGGGBRGBRRGRGGBRRGRGGBRGGGRGBGBBRGRRGBRBRGRBRRBGBGGGGGGBGGRRRRRGBGGGRGGBGBGGRGRGRGBGGRGRRRGRRBBRRRBBBRGRRRBRBRBRBBGGRGBRGGGGRRRGRBRGRBGRRGGRBGRBGBBGRGRGBGGRBGBRGRGGGGBGRGBBBBBGRGGGGGRGBBBGGBRBBGGRRRRRGBBBRRGGBBBRRRRGBBBGGRGGRBRRBRGBRGBGGRBBRBRGRRBGBRBGRGRRRRBGGRRGGRGGRRGGRGRGBBBBBBGGRBBBBGRGGGBGGGRBRGGRRGBRGBRBRBRRBBRBBGRRRRBBBRBBGRRRBGRRRGBGGRRRGRBRBBGRGBRRBBRBRRBBGRBRBRGRGBBBRBRRRRRGBRBGRBRRBRBBGRRGRBGBBGBBGRRGRRRBBBBBGBGGGRRBRRRGGBGRGGRRGRBRGBBGGGGBBBRRRBRBRRRGBBGGGGBRBGGGRRBGRGGRGRRRBRBBGRBGRRGGRRBBBGGRBBRRRGRRGGRGBBBGRGBGBRGBGRRGBBGBGGRBGGRRRRBBRBGRRRBBBRRGGGBGRGGBGGBBRRBRRBRGGGGBRGRBBGRGBRRRBBRRGRRBRGBGRRBRBBRBGRBGBRBBRBGGBGGGRBRGGBRBRRRGRGGRBGGBGGBRGRGGRRBRRRGGRBGGGGRBRGBRBGRBBBRGRBRGBRGGRRRRGBBBGBBBBRRBGRGBGBGBGGRBGGRGBRBRRBRBBRBGGRGBRBBGRRGGBGRRRGBRRRGGBBRGRRRGRGGGGGRGBRGBGBRRGRGGRBBRGRGBRBGBGRGGBBRGBGRBGBBRRRGGRGGRBRBRGGBBBRRGRGRRRBBBGGBGBGBRRGRBGBGBGRBRBRGRBRRGBRRRBRGBBGBRBRRRBGGGRGBRGBRBBGRGGRGBGRGGBGBGGBBGGGRGBRGBBBGGRBRRBBBBRGGBBRGGBGBRRGBBGGBGGRBBRRRGBRRBGGBGGRRGGBRGRBBBBGRRRRRRRRGRRGBBRGRBBRGGGGRBGBBRGRBGGBGGRRBGBBGRBBRGGGBBRGBRRGRBBBRGRRRGGRBGRGBRGRGBBBBRRBRRGGRGBGRBBRGGGRRBBBBGRRGRRGGRRBBBGRGRBGRBBGRGRGRBGRGGRBBGRRBGRGGBBBRBGGGRRBBRGBRRBBBRGRBBGBGBGBGGGGRRRBGBBRRGRGGRGBGRBGRRGGBGGGBGGRGBRRGBRBBBGRBBRRRBRGRGRRBBRBGGRBRRRRGBBRGRGRRBBGGBBBGRGGRGGGBBGRBBRGGRGRRRGBBGRGGRBBGRGBGRRGBBGBBRGGRBBBRGGRRBRGRBRGBRRRRBBBGRGGGBRBRRGRBRBBBBGBGBGRBBGBGRBRGGBRGRBBGGRGGRRRBGRGGGGGGRRRRGGBBGBGBBGRRBGGBBBBGRRBRBRGBBRRRBBRRRBRBRRGRBRRBRBRRBRRBBRGBRBRBBRRRRRRGGGBGBRRRBGGRBRBGRBGGGGGGBGGRBBBRRGBRGBRBGRRRRRRGBGBBRGRBRBRBBBRBGBGRBGRRGRRBGRRGBRRRGGRGGGRRRGBBRGGBGGRRRGRBBRRGGGBBBRBGGRGBBGRBRBRGGRGGBGRBRBGBRGBRBGGGBBRGRGGRGBBRGGBRRGRGRRRRBRGGGBBGBRRRBRBRBGGRRGBGBBBRRGRBGBRRBBRBGRBGRGBRGGGGRGRBBGBBBRBGRRBBRBGBRRRGRBBBRGRRRBRBGRBGRBBGBGRRBBBBGBGGBGRRRGGRRBRBRRRGBBRBBRRBRBGGRRRRGGRGBGRGGGRBGGRGGRGGBGRRBBGRRBRBRRBRRBBBRRGBBGGGBBGBGBBGBGGRRGRGGBGBBGGBBBBBGRGGRBRBRBRRRBGGRGBBBGBGRRBBGGBBBGGRGBRGGRGBRRRGBRRGGRBBBGBRGBRGGBGRGGRRBBRRRGGBGBGRRRBRRRGBRGRGRBBBGBBGBBGBRBBGGRBBGRRBRGGRBGBRGBBBBBRGGGGGGRRGRGRBGGBGRRBRRBGGBBBGGBRRBGBRBGGBBRRGBBRBBRRRRBBBGBGRGBRGGGBGRGGRGBGRGBRRBRBBRBGBGRRBRGBBRGRRBBGBGBBBGRGGBRRBBRRRRRRGBBRRGGRBRRGRRGBRRRGBGRBRRBGGRRRRBGGBBBGGBBGRGGRGRGGGBGRBGBBRBBGBRBGGGRRGBBBGRBRRGGRGRGGRRRGRBBRGBGRRBRBGBGBRGRBRRBGRRBGRRBGRBGBGRBBBBBGGGBBBBBRBGBGBRBRRBBGGGGGBRGGGRGRBRRRBBRBGRRRRRGGBGRBBBRGGBGBBBBBBGBBRRBBRRBGGGRRRGRRRGBGRGRGGGRGBRGRGGBRBRGRBBGRRBGGGGRRRGGBBBBBBGRGBRGGRRGRRGGGGBBBRBBGBRBGBGBBBBGGBRGGGRGGGRBBBRBRRBRBGBBRRGGBGRGGRBBBGGGBGGBGBBBBBBBRGGBBRGBGGRRBGRBBBGBGRBRBBBGBBGRRBRRRGBGRGBGRRRRBBBGBBBBBBBBBRRRGRGGRGGRBGBBGRRGRRGRRGRBRBBRRRGBGRRGGBRBRBBBRRGGGRBBGBGBBGGRBRRGRGBBGRGGRBGRRRBGGGRRGBBGBGBGGBRGRGBGGGGBRRRRRBBBBBBRBBGBGGRBRBBGRGGGBBGGBBGRBGRGGBGGGRRBBBBBGGBGRRRBRGRRGRGGBGBRRBBBRRRRBBRGGBRGRGGGRRGBRRGBGGRBRRRBGRBGRBRBRRGGBBRRBBRRRGBBBGRRGGBBGBGGBBGBBBBBGBRBBRBRGRRRGGGBBGRGRGRGGGGGRRGBRGGRGBRRBGBGRGGRRGGGRGBGRGRRBGGRRBRBBGRBRRRGGRBGGGGBRGRGRGRRRGRGGGRGRGGGGRRRRBBGRGGGGBRGRGBGBRBGGRBBBBRGBGBBRBGBBRRRRGGRRGRBGBBGRBGRGBBRGGRGGBGRBRRBBBRRGRRRGBGGBBGRBRGRBBBBGGBGGRRRRBRBRBBGGBRRGBGGGRBGBBRBGRRRGBRBGBBGGGGRRGGRGBGBRBGRBGBRBRRGBGRGGBRRBGGBRBRBBRGRBRRGRRBBGRBGGBBGRBBBGRBGRRGRGGRGGGBBBBRRBBGGGGBBRBGBRGBBBRBGGGBGRGRBRRRRRBGRRBBGBGBRRGBRBRGGGRRGBGGRRGRRRBRRGRBRBGGRBGRRGBGRBBGGRBBRRBBGBBGGRBBBRGRGRRGBBRRBBBGRBRGRRRBRRGBGGGGBGBRBRGGRGBRGBBGBRBRBRRBGRBRGGGRBGGGBBGRGGRBGRGRBGBGRBGGRRBBGGRGRBRBBBBBGRGBGRGRBGBBRRGBRRGGGBRBBBGBGGGRBRRGBBBGRGGGBRRBGBGRBRRGBBGGGRBGBRRGRRRRBGBGBGGRRBGRRGRBGGBRRGBBBBRBRRRBBBGBRBBBBRBRRBBBBBBBRBBBBRBBGBBRBRRRRBBBRRBGRRRBBRBGBGGGGGGBRRRRGRBGRBGBBGRRGGRBBRRBGGGGRGRBGBRGRBRGRGGBGGRRRGBGBRRRRBGRRRRRRGGRGGBGGRBRRBRGGGBRGRBGGGRGBRBBGGGRGRBRBGRRGRBRGBGGRGBGBRGBGRGRRRGGGGGGBGBGBGRBGGRBBRGBGBGRGGRGGRBRBGBBRGGBRBBBGBBRRGRBGBBBRRGBRGRRBBRBBBBBGBBBBBRRRRRGBBBRRRRBBGBBRBBBGBBBGBGGBGGBBGGBGGRBBGBBBGGRBGGRRRGRRRGBBRBBBBBGRRGRGGRGBRBBGGGBGBBRBRRBGGBBGBGGBBRBGRGRGRGRGBRGGRBGGBGGGGRBRGBGGBRBRGRBRGRBRRGGGRGBGBRBRRRBBBRRBGBBRRBRGRGRRBGBGBBBBRBGGRGGBGBGBGBRBBGGRBBGBRGRGGRGGGRRGGBBBGRBRRRRRBBGBGBBBGGGBGRGRGBRRGBRRRGGGBBBGGRGBRRBBGGGGBRBRRBRBGGGRBBBGGGRRBGBBBGGGRGRBBBRRBRRGGBGGGGRRBRRBBRBBGGGRRGBGRBGRRBRBGBBRGBRGGRGGRGGRRBRGGBBRRGRRGRRRRBGBRGRGRBRRRBGGGGRGBRGBGBRRGRGBGRGGGBRGBRRBBGGBGGRGGBRGGGBBGGBBGRGRRBBBRRBRBGBGBRBBBBGBRRBBRBRGRBBGBRRBRGBBBRRGGRGBBRGRBGGBGGRBGGRRGBBGRRBBGRGBGGBGGRRRRBBGRGRBRBRGBRRBGRBBBGRRBRBGBRBBBRRRGBRGBRRGGGGRBRRGGGBBBBGGGRGRRGGBGBGRRGBGGRBRGRBRBBRGBGRRBGGRGRBRRBBRRGBGRBBGRBBBBBBBGRRGBBGGBGBRRGGBGGGGGBBGBRGBBRBGBBRGBBRBRBGBBBBRRRBBRGGRBRRRGBBRBBBBGRRBRGGRRRRBBBGBGRRGGRGRRRGRRGRGBRRRBRRRGGRRRBGBRGGGBRRBGGRGRGBRBGRRGGRBBGGBRBRBGGGRBGGRRGRGRBGGRRGBGBBGGRGBRBGGGRRGGGBBRBGBRBGGRBGBBRGRGBBBBBGGBGRRRRRGRGGGBBBBBRBBGRBRGBBGGBRRRRBGRRRGBBBBGRGGRGRBBRRRBGBBRBRRRBBBRRRRBGBRGGBBBBBRBRGRGGBGGBBBRBGRRBGRGRGRGGRBRBBGRGGGBGRBRRGRRRGRBBRBBBBBGBGBRGRRBBBRRRBBRGBGGBRGGRRBRRGBRRBRBRGGRGBGGBRBRGGGRGGBRGBGBGGRGGRRGGRBBBGBRBBRRRRGBGBRRGGRRRGGGGRRGRBGRGRRGBBBGBGGGRGGBRBBGRBBRBBBRRRGGBRBGBBBBGRRBBBGRRGGGRRBRGGGGBRRBRRRRRGBGBRRBGGRBRGRGBRGRBRBBGRGBGRRGGRRGBGGGBGRGRGBRBBGBBBGGRGGGGBRBRRGBGRGGBGBRGRGRBRRGBRGBGBGBBBBBRRBBGRGGRGBBGRBRGGRGGGGBGGBRRGBGBBRGGBRBGBGRRGBGBRRGBBGRRRGRBGGBBRRGBRGGRBBRGBGBBBRGBRBRRGRGRRRRGRGRGBRGBRBGBGRBGGGRGRRRBBGRRGGGBBGGRGRBGBRGRGRRRGGBBBBBBGRBRGRRGBGGBBGGGGRRGRGGRBGBBBRGRRGGGGBBBBGGGRRRBRGRBBBRGGBBRRRRRBBBGRRRBBBRBRGGGRBRRGRRBGBRGBBRGBBGBRGGBBRGBGGRRRBRBRRRGBRGBRBGRGRBRBBBBRGGGBBGRGRRRRRBRBGRBRBBRRRRRRBBRGGBGRGBRBRGBRRRBBRBBGBBBBBBBRBBGRBGGGRBRRRRGGGGRBGRRGRRGRBGGBGRBGGBRGGGRBBGGGRBGBBBGRRBGRGBBGRRBBBGBGBBGBGBGGBRGBRBBRRGGGBBBRBRRBGBGGBRGRRRBRRBRRGRGBRRGBBGBGGRGRRRBRRGRGGGGBRBRBRBBRRGRBBRBBGGBBGGRBBGGBRRGRRBGGBGBRBBRBBBGGGBBRRBRGGBRBBBRRGGBGRGBRRRRGBBBGGBBRGRGGBBRBGGGRGRRGBBBRBRGRBBGBGGBGBGBGRRBBBRBRRBBRBBGBBBBBBBBBGBRGRRRGGBRRBGGGRGGRRBRRRBRRBGBGRBBBRBRGRBBRRGGGBGBRGRGGRGRRBBBGRGRGGGRBRRRGGGRGRRGBGBGGGGBBBGRBRRGBBGBRBBGRBBBBRGGGGRGRBRRGRRGRGRRRGRGBRGBBRRRBGBRRBBGBGGGGBRBRRRGBGRGGGBBGBBGGGBGBBBBRGRGRGGRGBRBRRRGGRGRRRBBRBGRGBBBRRGGBRBGBBGBRRBGRGBBBBGRGBRRBRBRGBBGBBGBRBBRBBRGGRRGBGGGGBGGRBBGGBRRBBRBGRGGBBBRBRBBGRGRRBBRBBRRGGBGRBGGRRRRBRGBRGGBBBRRRRGBRGGGBRRBRRBGRBBGGGRGRRBRBRGRRBRGGGGRBGRRBRGRBGBRRBRRBRGRRBRGBGRRBGGBRBRGBBBRGGGBRBBGBGBRGBBRGRGGBRBRRBGRBRRRGBRRBRBGBGBRRBBBBRGBGGBBRGRRBGBGRBBBBGBBBGRRGRRRRBRRRBRGGRBGBGRBGRRGGBGGGBBBBRRRBGRRRRBRGBBRRBGGRBGBBBRRGRRGGGGGBBBRRBRBBBRGBBRBGGGRRBGBRBRGGBBRBBGBRBBBRRRBRGRBBBRGBRRRBGGGGGBGBGRBGGBBBGGBBGGBBRRGRGGRRRGBBBRBRGBBBBGGRGGRRRBBRGGGRBBRRGBGRRRBGGBGRGBGRGBRRBRRRGBRBBGRRGBBGGGGBRBRBBBBBGRBRGBBRBRBBBGRGRRGBGBGBGGBGGBRBRBGGRGBRGBGGGBRRBBBGGGRBRRGBGBBGBGGRBRBBRRGRBGRGRBBBGRBBBGBRGBGRBBBBRGGBGRBRBRBGBBRBBRBGBBGRGGGRGRGBBBBRRGGGBRBGRRGRGRBRBBRBRRRGRGGRBRGRBRGGGGGBRBRGGBBRBRBBRRBBBGRGBGBBBGGGRRGRRBBGGGBGRBGGRGRGRRBBBBBGGRRBGBRBGBRGBRRRGGGGGBBGRRGBBRBGBRRRRGBBGGRGGRGBRBBGBBRRBGRRBRGGGRRBBRGGGRBGGGGGGRRGRRGRGBRBRRRGGRGRBGBRBBGRGGBRGBGBGRRBRGGRBRRRGBBRRBBRGGGRBRRBRBGGBBBRBGGGBGRBBRBRBBGGGBRRRRBRBBRBGRRRBBRBRGGRGGGGGBRBGRRGGGBGRBBBRBGRGBRRRBRGRGRBRRGGBRRRGRBBRGGGGRBRBBRBGBGGRGGBRRGBGBRRBBBRBBGGBRGBRRBGBGGRRRBRGGRRRRRRGGGGRRBRGGBRGRBGGRBBGGRGBRBRBRGGGRBBGGRRBBRBRRRBGBBGBRBGRGRRGGGGGRRRBRGRGGBGBRGBGRRRRRBGGBRRBGGGRRBBRRBBBBGRGRBBGRBBRBRBBGBBGBRGBRGRRGRGGBBBBBGRBGBBGRGGRGRGGGBRBRBRBRBGBBGGGGBRBBRGRBRRBGGRRRBRBGRGGGRRRRBBGBRRGBRGGRBRBRBRBGRBBGGGRBBGRGGGGGBBGBGGRRBRBGGBBBGGRBRGBBRBGGRBRRGBRGGGBRGGBRGGBBGRRGBBBRRRGGRBBBBRRRGRBGBGGGRGGBBGBBBGBRBGGBGGRGBGBGGGRBRRGBGBGGBGGBRRBRBRBRBRBBBBBRGBRBBGGGBRRBBGGRBRRGGRRBRBBBBGGGGBRGBBRBRRGRRBGBRGBBBRBGBBGBRRGBRBGRGBBBRGRRGBGGRRGRRGBRGRRBGGBBRGRBRBBRRRBBBRGRRBGGGRGBGBBRGGRBRRBRRBGRBRBBRGRGRGBBRBBBBGBRRBRRRRGRRGGGGGRRBGBBGBBGBBGGGRBBRGRGGRGBGBRRGBRRRRRBRRGRRBBGRGGGBBBGRRGGRBGGGRGRGBRBRBBRBGBRRGBGGBRGRBRGBGBGBBGRBBBBBBRGGRBBBBGGBGRBBRRBRGRBRBGRBGRGGGRBGGBBRGRBRGGRBRBBGBRBBBBGRBRBRGRBBBGRGRRBGBBGBBGRGBRBGBRGBBBBGBRGGGBRGBBRGBBBGGRGGGRBRGGRGRRBBRGBRRBBBRGBRGGBBBGRRBRGGGBRRBRBGBGGBGGRBBRBRBBRGRGBBGRBGRBGRBRGGRRBBRBGBBRGGGGBGGGBBBGGRGBGRGRRBBBGBBRGGGRRBRRBGRGGRRRGGRBBBRBGBGRGRRGBRBBBBGGRGRBGGRBRRBRRRBBRBRRRGBGGGGBGBGBRBGBGBBBRBRGRBGGBGGGGGBRRRBBGGBGGBGRGBBGBBRRRBGRGGGBBGGRBRRGBRRRBBGRBGRGGGGBRRBRGBRBRGBRBGGBGBRGBBBGGRRBBBBRRRRBBBBBRBRRRBRBBGRGRGRGGGBGRBBBBRGGBGBGRBGGBGGBRRGGGBRRGRBRRBBRRGBGBGBBGGGGGRRGGGRBGGRRBBRBBRBGGBBRGGRRRBGGRBRGGGGGBGGBBBGGRBBGBBGRGGRBGBRBGGGGBBBBGGGGRGRRRGBBRRRBBGBBRRBRBGGBRRRBGGRBBGRRBBBRRGRRBBRRRRRRGBBBBBBGBRRBBGRBGRRGGRRRRRBGGRGBRGRBGBBGRBRRBRBRGRRBGRGBGRGRGBRGRRBBRGRGGBBRBBGGRGBBBRBRGRGBRBBRBGGGRBBGGBRBGGRBRBBRRGRBBRRBBBGBGBRGBRRGBRGBBGBRBBRRGBGGBGGGGBGRBBBBRBGGRBRBGBRGBRBGRGRBRGRGGRBGBGGRRRGRRGGBBBGGBGRRBRRBBBGGBRRGGBBRBGGRBBRBGGBBGBRRRRRRRBGBRGGBGGRGBBBBBBRBGBBBGBGBRGBGRGGGGRBBGBRGGRRBRRGBRRBBRRBGBRRGGBBBBGBGBRBGGRRGBBGBRBBRBBRBRRGGRRBRRBBRBBGGRBGBBRBRBBGBBBBBRRGGGRBBBBBRBBGBBRBGGGBRGGRRRRRGGBGRBRRRBGRGRBGRGGGBRGBBRGRRGRRRBGGRBBGBRGBGGRGBBGGRBBBRGRRBBGBGBGBBGRBGBGGBBRGGGGBGGBGBRRBBGRBBGGGBRRBRBRBBRGGRRGGGGRGGRRGGRRGBBRBBGGGGBRGGGBGGRBRBRGGRRRRRGBRRBGGBRBGGBBBBGGGRGBRBGGRGBGRRGGBRRRRGRGBRRBBRRBGGBGGRGBRRGGBBRGGGBGBBGGRGRGBGRRBBRBRGGRBRBGRRBGGBRRGGBRRBGRRGBRRBBRRGBBBGBRGBGBBGRGRBGGBBBBRGGGRGRGGBBGGGGRRBRRGGBBRRGRGGRBRBGGGBRRGBGRGBRRBBRGRBGGGRGBBRGRBRBGBBGGRRBGBRBBRRGRRRBBGGGGGGGBBGGRRRBGRBGGRRGRGRBRRBBRRBGRGRRRGGRBBRGGBBRRBGBBBBBRGGRBGGBBBRRRBGRBBBRRGRGGBGRBRRBGRGBGBGGRRBRBGGGBRRBGRRGRBBRRRRRRGBBGGGGGRRGRGGBRGGBBBRRBGGRGGGBRRBRGGBRGBGBBBGRGRBGRGBRBRGRRBRGBBGGRGBRGGBGGBGRBGBRBGBBRRRGGRBGRBRBGBBBGBBRGRGBBGBBRGGGRGBBBBRRBBBRGBBRBGGBRRGBGGBBGGGBRRGBRBRBGRBGRRGRBRRBGBRRRRBBGRGBBBBBRBRGGBBGRGGRBBRGGRGRGRBRBGRGGBRGRRGGGRBGBBBBGRRGGBGGRRBRBBGBRBGRGBBBRBGRBGRBBGRGGGBBBGBRBRBBRRBGGBGBBGBBBRGBBGGRRBBBGBRRRBBRGBRBGGBBBGGBRBBBGGRBGRBBBRRRRBRGRGGBGRGGRBGRBGBGRRRGRGGBGGBGGRGGRBGGGRBGRGGRRGRRGGRGBGGRRGRBBGGBGRRBGRGBGBRBGRGRGGBGRGBGBRRRBBRGRGGBBRGGRGGBBRRBGRGBGGRBBRRGRRRRGBRGRBRRGBRGBGGGBBRGRRRRGGRGBRRRRRRRBGBBRRGRBBGGGBGBBGRRRRRRGRGBGGRBBRGRGBRGGBRRGGBGRRBGRRGBRRBBBRGBBRBGBGBGRRBRGBGRRGBGGBGBRGBBGRBRBRBGGBGBBRRBRBRGRBRBBGGBBGRGBBRBBBRGGBBBRRGGBGRGRRGGBRRBBRGBGBGGBBGGBGRRGBGBRBRGRGBRGGBRGGRRRGBRGGBRBRGRBBBRBRGRGGGGBRBGBRRBBBRRRBGRRBRBRGBBGBRRGGBRRGBBBBBBBGBRGBRBGGBGBRGGBBGRBGGBRGBBGGBGRRBBBBGRGRBGRGRRGBRRGBBBGGBRGBGGBGGGBBGRGGBBRRRBBGBRGRBBBRBGBGGGRBRBRBRGGRGGRGGGRBBGBRGBRGGBBRGRRGRRRBBBBGBGBRBRBGGBGBBBRGGGBRBBGRGRRRBBBGRRBRRBRBBBBBBGRRRRGBBRRRRRBGGGBBGBRRRGBBRBBBGRGGRRBBRRGBBGGRBGRBGRBBBBGRBRBGRGRGGRRRBBRGRGGGBGRGRRRBBBRBBRGRBRGGRRGRRBGGRRRBRRGGGGGGGBRGRBRBRBGGRBBGBRBBGBBGRGRBRGRBRRBRRBRRBGBRBGGGBGBGGBBBRRGGBGGBBRRGRGBRRBRRGBRGGBBRGRBBRGRBRBBGRRBGBBBBBRGRGGBBRBRBRRGGRBGRBGBBBGGBBRGGGRBBGBBBBRGBGRGGRRRBBBBGBRRGGRRRRBBRGBBGRBGBBRGBRBBRRBBBRGGBGGBBGGBGGBBGGGGGBGBBRBRGGRRRGBBRGGRRRRGGRRGBBRRGBRBRRBBBRGBBRGRBRGBGBGRBBBBBRRRBGRRBRRGGGBGBRGBBBBRBRGGRGRBBBRBRBGBBBGRRRBRBGRGGBGGRBRGGBGRGBRBGGBRRRBGGGBRRBBRRRBGRRBBBRRGBRRBBBRRGBBRBBRRGBGBRGRGBBGBRBGGRBRRRRGGGGBGRBGBBGBRBBBGRGGGRRBGRRBRBGBGBGBRGGBGBBBBRBGGRRBGRRBGGBBRGBGRGGGRRGBRGBRBGBRBBBRGRBRBBBRRBRGGGBBBBBRGGRRRRGBGGBBBRBGBBBGRBRBGGGGRRGGRRBRRRRGGRGGRGRGGRRGBRRGGBRGRBRRBBBGRBRRBBGGRBBBBBGBBBGBBBRGGBBBBGGRGGGGRBRBBBBGBBBBGGGBRRRBRBBBBRRRBBBRBBRGBRGGBRBGGGRBBGBRGBRGBGGBGGGGRGRRGGBGBBRGGGRGRRBBRRRRBGRGRBBGRRBBBGGBBGRGGBBBRBGRBBRRGGGBRBGBRRGBBRBGRRRGRRRRBBRRBGRRGBRBGGGGGRGBGGGGBBBBRRBRRRRBRGBGGRRBBBBBBRGGGRBBBBGBBBRBBGBBRBGBRBBBBGGBBRGGGRRGGBBGGRBBGGBBGGGGGGBRRGRRRGBBRRRGBRBGRGGRRRBGGBGBGRRGBGGBRRGRRRGGRBBGGGGGGGGRRRRGGGGRRBGRGBGGBRBGRBBBRRGBBRRRRRBGBRRBRGRBGBRGRGBGGBRRRBRBRRBRGRBGRRRGGGRBRGGBRGRGRGBGRBGRBGGGGGRBBGGRRBRGGBRGRGRBBRGRRBGRBRBRBRRGGBGBBRGRBBBRGRRRGBGBBRRGGRRGRGRGGRGRRRRBBRRRGGBBGRGRGGBGGRBBGRBRRRGRGRRRRGBGRGGGBRGBRGRBGRBGRGBGBRBGRRGGBGRRBBGRRRBGRBRBBRRBBBGBRGRGGRRGGGGBRRBGRGBGGGGRGGRBGBGBGBRRBGGRRBBGRBRRRRBBBRRBBGGGGBRBGBBGGGBGGBBGBRBRBGGGBGGRBBGGBRRGRRRGGRRRRRGRGGBGRRBGGBGBGRRGRBGRBBBBRBBRRBBBGGRGBRRRBBBGRGRRRGBRRGBRGRBGRGGGBGRGGGBBRRRGGGBBRGBRRRBGGGRGBGRBBGRBBRGGRBBBRBGGGGBBBGRRRBBBRRGGGBGBBRRRBRRRGBBBGBBRGGGGRGRGGBBBGGGGGBBGGRBBBBBGGBBRRRGRGBGBBBBRRGBBGBGBBRBBBBRGBBGBRRRGBBGGBRBGBBGGGBGGRGRRGRRRRGRRBGBBRRGGGGBGRRRBBBRBRRGBGGRBRGBBBGBGBGBBBBRGBGRGRBBBRGBBBRGBBBRRGBGBGGGGRBBRRGGRGGRGBRRGGRBRRBRBBBGGGBBGGRGBBGGRBGGRBRGRGGBGRRRRRRGGBGGBGRGRBRGRBBRBBBRGGRBGRGBRGGRGBBRGBRBRRRRRRRRRBGBRBBRBRRGBGGGBGBRGBGGGGGBBBBGBGRRRRRGBGBGRGRBBRRRRGRGGBGRBGGGGBGBRRRRGBGBGRBRRGBGBRRGBBBGGGRBGRRBRRBBGGRRGBBBRBGGBBBGGBRRGGGBGGBBBGBGRBBBBGBGRGRBRBGBRBRGGBGBRRBBBBGBBGBBBBRRRRBBGRGGRBRBGGGBBGRGGBRGRGGRRGRGRBRBRRGGRGRRRRBBBBGGBBBBRGBGRBGGBGRGBGBGRGBRBGRGBBRGGGBRBGGRBBGGBBBBRRGRBRGBRGGRRBBRGGRGGBBRRGBRGRBBRGGRBBBBBRBRRBRBRGGGBGBBBBBGBBGRGRGGBRRBGGRRRGBGGRGRGRBBRBRBGBRRBGBRBBRGRGBGRGRGRGBBBGGRGRRBRBRGRRBGGBRBGBGBRGGGRRGBBRRRRGRBRBRGBBBGBBGRBBRRGGGGBRGGGBBGGGGBGGRGRGRRRGGGRRGBGRRBGBGBBBGRRRBBBGRGBRBRBGGBGRGGGBRRRGRBRBGGRRRRGBGGRRBRGRRGGRBRBBGRGGRRRBBGBGBBRRGRGRRRBBGGBGBBRRRRGGRGRBRRRBRGRBBBRRRBRBGBGRBBRRBGGRGBRBBGBRRBRRBRGRGBRBGBRGRRGBRBRGBGRBBRRRGRRGGBBBGBBRRRBRRRBGGRRRGBRBBGBRBRBGRGGBBRBBRBBBGBRRRGRBRBBRRBBRRGBRRRRBGRGBRGBGRRGGBBBRBGRRGBGGGRBBRRGBGRRGGBRBRBGRGRRGBBBGBRRGRGRRGBGRBGGGRBGBGBBGRRRRBBGBRRGGBGBGGRBGGRRRGGBBGGGBBGBBGBBBRRRBGRRRRBBRGRRBGRBRBGBBRGGRGGBGGRRGGBBGGGBRGRRRRRRRBRRRRBRGGRRRGGBBRBGRGBRGBBGGBRBBRBBRBGBRBRBGGGRBRBRRBRGBBRGBRRBBRRRBGRGRRRBRGBBRBBGBRBBGBRGGGBRGBGRGBBBBBGBBGBRGBGRGRRRRGBGBGBRRGBBRGGRBBGGGGGRBRGRRBRGRRGGBRGRBGRRGBGRBRBGGRGRGRGGBBRRRGGBBGBBRRRGRGBRBGGRBRBRRRBRGRGGGRGGBGGBBGGBRRRRRGRBBRRRBBRRRRBBRRGRGBBGGGGBBGBBGGBRGBGGRBBRBGRRBBRBBGGGBRGBBGBRBBGGBRGBBRGRRGGRRRBRGBBRBGRGBRBBBGBBBGBGGRBBBGRRGRGRBRRBRGBBBBRBRRBBGBGRBBRGGGRRBGRRRGBRGGRGRRRGRRGGRGBBGRBBGBBGGRGGGBGRGBGBRRGBGGGGRGGGGGGRRGBBGGGRRRGBRBBRRGBGRGBRBBGBRRRBGRBBBRRRGBBGBBRRBRGBBBRRBBBBRBGGGRBRBRRRBGBGGRBRRBRRGRGGRRRRRBBGRGBBBGRGRRRGRRBGBRBGGRBGGBBRBBBGGRRRGGGGBGRRBRBGRBBGRBRBBBBBBRRRRGRBRBRRGGRGBRRBRRBGBBRBBGBBBRBBBRBRRBGGGGRRBGGRBRGGRBBRRBBRBGRBBBRBGGGGBRGBGBBRRRBRRBGGGRBBBRGGRBGBRGRRGBRRBRGGGRBBGGGRGGBGBGRBRRGGGBBRBRRBRGGBBGBRBGGGRRBBRGBRGBBBBBBGBRGBGRBGBBBGRGRGBGGBBBGGGGRRRRBBRRBBGBRRBRBBGRGGBGGGRBBGRRGGGGRBGRGGRBBBRBRBRBGBRRGRRGBBGGRBBGBBBRRBRBRRBRRRBGBRBGGRBBBGRBGGGRRGGGBBGBBBBBBBBRRGGBGBBGRRBBGRBBBGGBRRGRRRGBBRBRGBRGGRRGRBGBRGBRRGBRBGRBGGGGBBBBBRRRRGBGGGGBBRBRGBRRRGRBGBGGBBRGRGBGRGRGBBRBBRBBRRRRRGRGGBRRBGBRBGBRBBGRGBRGBRRBGBRGGGRBGGRGRBGBRRRRBBRGBGRBBGBGGRGBBGGGRGBRGGGGBBBRBRGGBBGGBGGRBBGGGBRBBGRRRBRBGRBGRBRRBBBGGRRGBGRBGGGGBBRBBRGGRBBGGGGGGBRRBGGRRGBGRGGBRGGRGGBBGBRRRRGBBBRBRGBRRBRGRGGBBRBGBGRRGGGBGBBRBBRBGRGBRGGGBBRBRGRRBGGGBBBBBGBGBRGRBBRRGGGRBRRBGGRGBBGBBRGGBGBGRRRRGRRBRBGRRGBBRRGRRBRRRBGBBGBRBBRRRGRGRBGBRBGGRBRGBRGRRRGBGRBGRRGGGBGBGBGRBRBGRBBGRBGGBRGGRGRGGGGRBBBGGGGBBBRRGRGBRGGRGBBRGBGBGBBRGBBGGGGGGBGRRRRGGRBRBGRGRBGBBBRBBRGRBRGGBRBBRRRBRBRGGRRBRGBGRRGRRBRRRBGBRGBGBGBRGBGRRGBBGBRBBBRRGGGGBRGRRRGRGGRRRRGBBRGRRBGRGBGRRBBBRGRRGBRGRBBBBRBGGGRBRGRBRGRGGRBGGBBRBRBRBGRGGRGRGGBBBRGRGBBBBGBGGBBRBBGBRBGRBBGRRGBRBGGRGGGGRRBGBBRBBGBRBGRGGGRRGRGRBRGRBBRBRBBRBBRBGRRRGRRGRRGGRRBRRRBRGBRBGRRBBGGRGBBGRBBGRGRRGBGRBGRGRGGBGBGGRGRBRBRGBRBBGBRGBBGRRBGRBRRGBBRRGRRBRGGRBBBGGBBGRRBRGRGRBBGBGGGRBBRRRGRBRRBRGGBGBGGRBRGGBBGGBRBGBBRBRRRBGBBRRGGRRBGBRBGBBRGBRRRBBGBGRRRBBBBGGRGGBGGRGBGGRBRGGGGRRGBRGBBBBGRGGBRBGBBRBRGRGBBBGGRGRRBGRGGRGBBBBRGGBBGGBRBGRBRGGGRGGBRGBBBRGBRGRRRBBGGBBBGRGGGRRRGBBGBBRGRRGBGGBGGGGGGGRBBBBGBRGRRBBBGRRRRRBBBBGGGRBBGRRRRBBBBRRRBBBBRGRGGRGRRRBGRBRBRGGRGGBGBRBRGBRBRRGBGRRGGGBBRRGBBRBRGRBGRBGBBGBRBRRRGRGBBGGRBRBGGBRRBRGRRRBBGBBRRBGGGRGRGRGBGGGRGGRRRRGRRBGBGGRRBRGRRRGRGGBBBRRGRGRRBBGBGBGGGRBGRRBGGRBRGGRBRBGRGGGRGBBRRBBBBGRRRBBGRBBBGGBGRRBGBGGGBRGRBBBBRBRRBGRBRBBBRGBGRBBRGRGGBRGBBRRRRGGBBGBBBBRRGBBBGGBRRGGRBBBBRRRRBBRGGRBRRBGBBRBRBGGRGBRRRGRRGGGRGBRBBRGRBRRBGBBRGGGBGBRGRGBBRRRBRRBRRRGRGBRBGRGRGRRRBGBRRBRRRRBGBBRRRGBBGBBRBRRBRGRRRGGRGGGBGGGRGGBRRGBGRGGGRBGRGGGGRBBBRGBRRRGBBRBRGBBRBGGBRBBGGGRBGRGRGRRBGBBGGBGBBRBGGGRRRRBBBGBGGGBRBBGGBGGRRBGRGGBRRBRGGGRRBRBGBGGBGRGGGBBRRRRGBRBRRRGGBRRGRBBBGGGRBGBRRBGRRBGRRBRGBBRBRGRRRBGBRRRRGRBBBRBRRBGRGBBGBRRBGGBBRGBGBRBRGBBGBRBRRRGGRGRRBRBGGRGBGGGRBGBRRGBGBGBBRGRGRGBRBBBGBRRBBRRGGBGRBGGGRRGGGBRBGRRGBRRRRGBRGRGGRBGBGBGRBBGGRBGBRBRRBRGRBGRGGGBBGRBGBGGBGRBGGGGGRBBRRRRRBGBGBGGGRGRRBGGGBRRRGGBGGBBBRBBRRBBRBRBBBRRGBGGBGGRRRRBRBGBRGBRGRRBBGRBRGBRRBGRRRRGGGRGGBGBRBRRRGRBBGBRBBGRGRGBGBGGGBBBBBBGBRGBGBBGGGBGGGBRBRRGGGBBRBBRBBGBBRBGRGBBRBGBRGBGRBBGGBGBBRRBRGBRBBGGRGRBGBBBBGGBGRRRRGBRBRRRBBGRGRGRBBBGRGBBRRBBBRBBGBRGBGBBGGRRBGRGGRGBBRBRRGRBGBRRBGBBRBBGRBBBGRBGGGRBGRBBBRBGRRBRGBRGBRRRRRGBGRRBBBGRBBBBRBRRBGGBRBGBBBRRBGRRBGRGRRBRRBRRBGRBBBBGBGRBRGRRRGGRRBBGBBRBBRRGBGGRGGGGBBRBBGRBRGGGRRBGRBGRRBGGRBGBRRRBBGBGRRBRGRBRGGGBBBBRGGBBGGBBGBRBBRRBGRRRRBRRGGRGGRBRBBRGGRGBRBBBBRGGRBBBBBRGBRBGGBGGBBBRBGRGRRRGGRRBBBGBRBGBRRRGGGBRBRGGGBRRRGBGBBBGBGGBGRBGBBRRGGGRGBRRBRRGGBRRBBRBGBBRRGGBRBRGRGBGGRRRRRGRGBGGBBRGBRGRGBRBBRRRBRBRGBGBRGRBGGRRGGBGGRGRGBBGRGGBBGBGGGGBBGBGBRRRBRBGGRBBRBGRRRBRBBGGGBGGRRGGGGBGGBRBBBRRBGGRBGGBRBGBRBBGRRBBBBRGGGGGRGBRGGRGRGGGBBGRBGGRBBRGGRBRGRBBRBBBGGRGRRRBRGRRRRGBBGGGBGBGRGRRGGRBRGGRGBGBGGRRGBBGGBBRRGBRRRGBBGBBRGRGRBG"};


  n = sizeof(test)/sizeof(char*);
  for (i=0;i<n;i++)
  {
    length = strlen(test[i]);
    printf("mix()==%c, triangle==%c\n",/*defaultMix(test[i],length)*/'@',myTriangle(test[i]));
  }





}
